using Qisi.Editor.Expression;
using Qisi.Editor.Properties;
using Qisi.General.Controls;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
namespace Qisi.Editor.Controls
{
	public class FormulaEditor : UserControl
	{
		public enum FormulaMode
		{
			数学,
			化学
		}
		public enum GroupName
		{
			符号,
			分数,
			上下标,
			根式,
			积分,
			大型运算符,
			括号,
			函数,
			导数符号,
			极限和对数,
			运算符,
			矩阵
		}
		private List<FLabel>[] FLabelLists = new List<FLabel>[12];
		private List<Label> Labels = new List<Label>();
		private FlowLayoutPanel[] FlowLayoutPanels = new FlowLayoutPanel[12];
		private List<PopupHost> PopupHosts = new List<PopupHost>();
		private Size labelsize = new Size(48, 48);
		private int id1;
		private int id2;
		private int id3;
		private FLabel fLabel2;
		private FLabel fLabel3;
		private FLabel fLabel4;
		private FLabel fLabel5;
		private FLabel fLabel6;
		private FLabel fLabel7;
		private FLabel fLabel8;
		private FLabel fLabel9;
		private FLabel fLabel10;
		private FLabel fLabel11;
		private FLabel fLabel12;
		private FLabel fLabel13;
		private FLabel fLabel14;
		private FLabel fLabel15;
		private FLabel fLabel16;
		private FLabel fLabel17;
		private FLabel fLabel18;
		private FLabel fLabel19;
		private FLabel fLabel20;
		private FLabel fLabel21;
		private FLabel fLabel22;
		private FLabel fLabel23;
		private FLabel fLabel24;
		private FLabel fLabel25;
		private FLabel fLabel26;
		private FLabel fLabel27;
		private FLabel fLabel28;
		private FLabel fLabel29;
		private FLabel fLabel30;
		private FLabel fLabel31;
		private FLabel fLabel32;
		private FLabel fLabel33;
		private FLabel fLabel34;
		private FLabel fLabel35;
		private FLabel fLabel36;
		private FLabel fLabel37;
		private FLabel fLabel38;
		private FLabel fLabel39;
		private FLabel fLabel40;
		private FLabel fLabel41;
		private FLabel fLabel42;
		private FLabel fLabel43;
		private FLabel fLabel44;
		private FLabel fLabel45;
		private FLabel fLabel46;
		private FLabel fLabel47;
		private FLabel fLabel48;
		private FLabel fLabel49;
		private FLabel fLabel50;
		private FLabel fLabel51;
		private FLabel fLabel52;
		private FLabel fLabel53;
		private FLabel fLabel54;
		private FLabel fLabel55;
		private FLabel fLabel56;
		private FLabel fLabel57;
		private FLabel fLabel58;
		private FLabel fLabel59;
		private FLabel fLabel60;
		private FLabel fLabel61;
		private FLabel fLabel62;
		private FLabel fLabel63;
		private FLabel fLabel64;
		private FLabel fLabel65;
		private FLabel fLabel66;
		private FLabel fLabel67;
		private FLabel fLabel68;
		private FLabel fLabel69;
		private FLabel fLabel70;
		private FLabel fLabel71;
		private FLabel fLabel72;
		private FLabel fLabel73;
		private FLabel fLabel74;
		private FLabel fLabel75;
		private FLabel fLabel76;
		private FLabel fLabel77;
		private FLabel fLabel78;
		private FLabel fLabel79;
		private FLabel fLabel80;
		private FLabel fLabel81;
		private FLabel fLabel82;
		private FLabel fLabel83;
		private FLabel fLabel84;
		private FLabel fLabel85;
		private FLabel fLabel86;
		private FLabel fLabel87;
		private FLabel fLabel88;
		private FLabel fLabel89;
		private FLabel fLabel90;
		private FLabel fLabel91;
		private FLabel fLabel92;
		private FLabel fLabel93;
		private FLabel fLabel94;
		private FLabel fLabel95;
		private FLabel fLabel96;
		private FLabel fLabel97;
		private FLabel fLabel98;
		private FLabel fLabel99;
		private FLabel fLabel100;
		private FLabel fLabel101;
		private FLabel fLabel102;
		private FLabel fLabel103;
		private FLabel fLabel104;
		private FLabel fLabel105;
		private FLabel fLabel106;
		private FLabel fLabel107;
		private FLabel fLabel108;
		private FLabel fLabel109;
		private FLabel fLabel110;
		private FLabel fLabel111;
		private FLabel fLabel112;
		private FLabel fLabel113;
		private FLabel fLabel114;
		private FLabel fLabel115;
		private FLabel fLabel116;
		private FLabel fLabel117;
		private FLabel fLabel118;
		private FLabel fLabel119;
		private FLabel fLabel120;
		private FLabel fLabel121;
		private FLabel fLabel122;
		private FLabel fLabel123;
		private FLabel fLabel124;
		private FLabel fLabel125;
		private FLabel fLabel126;
		private FLabel fLabel127;
		private FLabel fLabel128;
		private FLabel fLabel129;
		private FLabel fLabel130;
		private FLabel fLabel131;
		private FLabel fLabel132;
		private FLabel fLabel133;
		private FLabel fLabel134;
		private FLabel fLabel135;
		private FLabel fLabel136;
		private FLabel fLabel137;
		private FLabel fLabel138;
		private FLabel fLabel139;
		private FLabel fLabel141;
		private FLabel fLabel143;
		private FLabel fLabel144;
		private FLabel fLabel145;
		private FLabel fLabel146;
		private FLabel fLabel148;
		private FLabel fLabel150;
		private FLabel fLabel151;
		private FLabel fLabel152;
		private FLabel fLabel153;
		private FLabel fLabel154;
		private FLabel fLabel155;
		private FLabel fLabel156;
		private FLabel fLabel157;
		private FLabel fLabel158;
		private FLabel fLabel159;
		private FLabel fLabel160;
		private FLabel fLabel161;
		private FLabel fLabel162;
		private FLabel fLabel163;
		private FLabel fLabel164;
		private FLabel fLabel165;
		private FLabel fLabel167;
		private FLabel fLabel168;
		private FLabel fLabel169;
		private FLabel fLabel170;
		private FLabel fLabel171;
		private FLabel fLabel172;
		private FLabel fLabel173;
		private FLabel fLabel174;
		private FLabel fLabel175;
		private FLabel fLabel176;
		private FLabel fLabel177;
		private FLabel fLabel178;
		private FLabel fLabel179;
		private FLabel fLabel180;
		private FLabel fLabel181;
		private FLabel fLabel182;
		private FLabel fLabel185;
		private FLabel fLabel186;
		private FLabel fLabel187;
		private FLabel fLabel188;
		private FLabel fLabel189;
		private FLabel fLabel190;
		private FLabel fLabel191;
		private FLabel fLabel192;
		private FLabel fLabel193;
		private FLabel fLabel194;
		private FLabel fLabel195;
		private FLabel fLabel196;
		private FLabel fLabel197;
		private FLabel fLabel198;
		private FLabel fLabel199;
		private FLabel fLabel200;
		private FLabel fLabel201;
		private FLabel fLabel202;
		private FLabel fLabel203;
		private FLabel fLabel204;
		private FLabel fLabel205;
		private FLabel fLabel206;
		private FLabel fLabel207;
		private FLabel fLabel208;
		private FLabel fLabel209;
		private FLabel fLabel210;
		private FLabel fLabel211;
		private FLabel fLabel212;
		private FLabel fLabel213;
		private FLabel fLabel214;
		private FLabel fLabel215;
		private FLabel fLabel216;
		private FLabel fLabel217;
		private FLabel fLabel218;
		private FLabel fLabel219;
		private FLabel fLabel220;
		private FLabel fLabel221;
		private FLabel fLabel1;
		private IContainer components = null;
		private ToolTip toolTip1;
		private FlowLayoutPanel flowLayoutPanel2;
		private FlowLayoutPanel flowLayoutPanel1;
		private Label label1;
		private Label label2;
		public FormulaEditor()
		{
			this.InitializeComponent();
			IntPtr dC = NativeMethods.GetDC(IntPtr.Zero);
			int deviceCaps = NativeMethods.GetDeviceCaps(dC, 88);
			int deviceCaps2 = NativeMethods.GetDeviceCaps(dC, 90);
			PointF pointF = new PointF((float)deviceCaps / 96f, (float)deviceCaps2 / 96f);
			NativeMethods.ReleaseDC(IntPtr.Zero, dC);
			this.labelsize = new Size((int)((float)this.labelsize.Width * pointF.X), (int)((float)this.labelsize.Height * pointF.Y));
			for (int i = 0; i < this.FLabelLists.Length; i++)
			{
				this.FLabelLists[i] = new List<FLabel>();
			}
			for (int i = 0; i < 11; i++)
			{
				this.Labels.Add(new Label());
				this.Labels[i].AutoSize = false;
				this.Labels[i].Size = this.labelsize;
				this.Labels[i].BorderStyle = BorderStyle.FixedSingle;
				this.Labels[i].Cursor = Cursors.Hand;
				this.Labels[i].Margin = new Padding(0, 0, 0, 0);
				this.Labels[i].ImageAlign = ContentAlignment.MiddleCenter;
				this.Labels[i].Click += new EventHandler(this.FormulaEditor_Click);
				this.toolTip1.SetToolTip(this.Labels[i], (i + FormulaEditor.GroupName.分数).ToString());
				this.flowLayoutPanel1.Controls.Add(this.Labels[i]);
			}
			this.Labels[0].Image = Resources.图片1;
			this.Labels[1].Image = Resources.图片2;
			this.Labels[2].Image = Resources.图片3;
			this.Labels[3].Image = Resources.图片4;
			this.Labels[4].Image = Resources.图片5;
			this.Labels[5].Image = Resources.图片6;
			this.Labels[6].Image = Resources.图片7;
			this.Labels[7].Image = Resources.图片8;
			this.Labels[8].Image = Resources.图片9;
			this.Labels[9].Image = Resources.图片10;
			this.Labels[10].Image = Resources.图片11;
			this.fLabel1 = new FLabel();
			this.fLabel2 = new FLabel();
			this.fLabel138 = new FLabel();
			this.fLabel139 = new FLabel();
			this.fLabel141 = new FLabel();
			this.fLabel143 = new FLabel();
			this.fLabel144 = new FLabel();
			this.fLabel145 = new FLabel();
			this.fLabel146 = new FLabel();
			this.fLabel148 = new FLabel();
			this.fLabel150 = new FLabel();
			this.fLabel151 = new FLabel();
			this.fLabel152 = new FLabel();
			this.fLabel153 = new FLabel();
			this.fLabel154 = new FLabel();
			this.fLabel155 = new FLabel();
			this.fLabel156 = new FLabel();
			this.fLabel157 = new FLabel();
			this.fLabel158 = new FLabel();
			this.fLabel159 = new FLabel();
			this.fLabel160 = new FLabel();
			this.fLabel161 = new FLabel();
			this.fLabel162 = new FLabel();
			this.fLabel163 = new FLabel();
			this.fLabel164 = new FLabel();
			this.fLabel165 = new FLabel();
			this.fLabel167 = new FLabel();
			this.fLabel168 = new FLabel();
			this.fLabel169 = new FLabel();
			this.fLabel170 = new FLabel();
			this.fLabel171 = new FLabel();
			this.fLabel172 = new FLabel();
			this.fLabel173 = new FLabel();
			this.fLabel174 = new FLabel();
			this.fLabel175 = new FLabel();
			this.fLabel176 = new FLabel();
			this.fLabel177 = new FLabel();
			this.fLabel178 = new FLabel();
			this.fLabel179 = new FLabel();
			this.fLabel180 = new FLabel();
			this.fLabel181 = new FLabel();
			this.fLabel182 = new FLabel();
			this.fLabel185 = new FLabel();
			this.fLabel186 = new FLabel();
			this.fLabel187 = new FLabel();
			this.fLabel188 = new FLabel();
			this.fLabel189 = new FLabel();
			this.fLabel190 = new FLabel();
			this.fLabel191 = new FLabel();
			this.fLabel192 = new FLabel();
			this.fLabel193 = new FLabel();
			this.fLabel194 = new FLabel();
			this.fLabel195 = new FLabel();
			this.fLabel196 = new FLabel();
			this.fLabel197 = new FLabel();
			this.fLabel198 = new FLabel();
			this.fLabel199 = new FLabel();
			this.fLabel200 = new FLabel();
			this.fLabel201 = new FLabel();
			this.fLabel202 = new FLabel();
			this.fLabel203 = new FLabel();
			this.fLabel204 = new FLabel();
			this.fLabel205 = new FLabel();
			this.fLabel206 = new FLabel();
			this.fLabel207 = new FLabel();
			this.fLabel208 = new FLabel();
			this.fLabel209 = new FLabel();
			this.fLabel210 = new FLabel();
			this.fLabel211 = new FLabel();
			this.fLabel212 = new FLabel();
			this.fLabel213 = new FLabel();
			this.fLabel214 = new FLabel();
			this.fLabel215 = new FLabel();
			this.fLabel216 = new FLabel();
			this.fLabel217 = new FLabel();
			this.fLabel218 = new FLabel();
			this.fLabel219 = new FLabel();
			this.fLabel220 = new FLabel();
			this.fLabel221 = new FLabel();
			this.fLabel3 = new FLabel();
			this.fLabel4 = new FLabel();
			this.fLabel6 = new FLabel();
			this.fLabel5 = new FLabel();
			this.fLabel7 = new FLabel();
			this.fLabel8 = new FLabel();
			this.fLabel9 = new FLabel();
			this.fLabel10 = new FLabel();
			this.fLabel23 = new FLabel();
			this.fLabel36 = new FLabel();
			this.fLabel13 = new FLabel();
			this.fLabel24 = new FLabel();
			this.fLabel37 = new FLabel();
			this.fLabel14 = new FLabel();
			this.fLabel25 = new FLabel();
			this.fLabel38 = new FLabel();
			this.fLabel11 = new FLabel();
			this.fLabel27 = new FLabel();
			this.fLabel39 = new FLabel();
			this.fLabel12 = new FLabel();
			this.fLabel28 = new FLabel();
			this.fLabel40 = new FLabel();
			this.fLabel15 = new FLabel();
			this.fLabel29 = new FLabel();
			this.fLabel41 = new FLabel();
			this.fLabel16 = new FLabel();
			this.fLabel26 = new FLabel();
			this.fLabel43 = new FLabel();
			this.fLabel49 = new FLabel();
			this.fLabel56 = new FLabel();
			this.fLabel17 = new FLabel();
			this.fLabel30 = new FLabel();
			this.fLabel44 = new FLabel();
			this.fLabel50 = new FLabel();
			this.fLabel57 = new FLabel();
			this.fLabel18 = new FLabel();
			this.fLabel31 = new FLabel();
			this.fLabel45 = new FLabel();
			this.fLabel51 = new FLabel();
			this.fLabel58 = new FLabel();
			this.fLabel19 = new FLabel();
			this.fLabel32 = new FLabel();
			this.fLabel42 = new FLabel();
			this.fLabel52 = new FLabel();
			this.fLabel59 = new FLabel();
			this.fLabel20 = new FLabel();
			this.fLabel33 = new FLabel();
			this.fLabel46 = new FLabel();
			this.fLabel53 = new FLabel();
			this.fLabel60 = new FLabel();
			this.fLabel21 = new FLabel();
			this.fLabel34 = new FLabel();
			this.fLabel47 = new FLabel();
			this.fLabel54 = new FLabel();
			this.fLabel61 = new FLabel();
			this.fLabel22 = new FLabel();
			this.fLabel35 = new FLabel();
			this.fLabel48 = new FLabel();
			this.fLabel55 = new FLabel();
			this.fLabel62 = new FLabel();
			this.fLabel63 = new FLabel();
			this.fLabel78 = new FLabel();
			this.fLabel64 = new FLabel();
			this.fLabel79 = new FLabel();
			this.fLabel65 = new FLabel();
			this.fLabel80 = new FLabel();
			this.fLabel66 = new FLabel();
			this.fLabel81 = new FLabel();
			this.fLabel67 = new FLabel();
			this.fLabel82 = new FLabel();
			this.fLabel68 = new FLabel();
			this.fLabel83 = new FLabel();
			this.fLabel69 = new FLabel();
			this.fLabel84 = new FLabel();
			this.fLabel70 = new FLabel();
			this.fLabel85 = new FLabel();
			this.fLabel71 = new FLabel();
			this.fLabel86 = new FLabel();
			this.fLabel72 = new FLabel();
			this.fLabel87 = new FLabel();
			this.fLabel73 = new FLabel();
			this.fLabel88 = new FLabel();
			this.fLabel74 = new FLabel();
			this.fLabel89 = new FLabel();
			this.fLabel75 = new FLabel();
			this.fLabel76 = new FLabel();
			this.fLabel77 = new FLabel();
			this.fLabel90 = new FLabel();
			this.fLabel91 = new FLabel();
			this.fLabel92 = new FLabel();
			this.fLabel93 = new FLabel();
			this.fLabel94 = new FLabel();
			this.fLabel95 = new FLabel();
			this.fLabel96 = new FLabel();
			this.fLabel97 = new FLabel();
			this.fLabel98 = new FLabel();
			this.fLabel99 = new FLabel();
			this.fLabel100 = new FLabel();
			this.fLabel101 = new FLabel();
			this.fLabel102 = new FLabel();
			this.fLabel103 = new FLabel();
			this.fLabel104 = new FLabel();
			this.fLabel105 = new FLabel();
			this.fLabel106 = new FLabel();
			this.fLabel107 = new FLabel();
			this.fLabel108 = new FLabel();
			this.fLabel109 = new FLabel();
			this.fLabel110 = new FLabel();
			this.fLabel111 = new FLabel();
			this.fLabel112 = new FLabel();
			this.fLabel113 = new FLabel();
			this.fLabel114 = new FLabel();
			this.fLabel115 = new FLabel();
			this.fLabel116 = new FLabel();
			this.fLabel117 = new FLabel();
			this.fLabel118 = new FLabel();
			this.fLabel119 = new FLabel();
			this.fLabel120 = new FLabel();
			this.fLabel121 = new FLabel();
			this.fLabel122 = new FLabel();
			this.fLabel123 = new FLabel();
			this.fLabel124 = new FLabel();
			this.fLabel125 = new FLabel();
			this.fLabel129 = new FLabel();
			this.fLabel130 = new FLabel();
			this.fLabel126 = new FLabel();
			this.fLabel131 = new FLabel();
			this.fLabel132 = new FLabel();
			this.fLabel127 = new FLabel();
			this.fLabel133 = new FLabel();
			this.fLabel134 = new FLabel();
			this.fLabel128 = new FLabel();
			this.fLabel135 = new FLabel();
			this.fLabel136 = new FLabel();
			this.fLabel137 = new FLabel();
			this.fLabel1.Cursor = Cursors.Hand;
			this.fLabel1.Ftype = FType.分式;
			this.fLabel1.Margin = new Padding(5);
			this.fLabel1.Name = "fLabel1";
			this.fLabel1.Size = new Size(30, 30);
			this.fLabel1.TabIndex = 6;
			this.fLabel2.Cursor = Cursors.Hand;
			this.fLabel2.Ftype = FType.斜分式;
			this.fLabel2.Margin = new Padding(5);
			this.fLabel2.Name = "fLabel2";
			this.fLabel2.Size = new Size(30, 30);
			this.fLabel2.TabIndex = 1;
			this.fLabel138.Cursor = Cursors.Hand;
			this.fLabel138.Ftype = FType.加减号;
			this.fLabel138.Margin = new Padding(5);
			this.fLabel138.Name = "fLabel138";
			this.fLabel138.Size = new Size(20, 20);
			this.fLabel138.TabIndex = 0;
			this.fLabel139.Cursor = Cursors.Hand;
			this.fLabel139.Ftype = FType.无穷;
			this.fLabel139.Margin = new Padding(5);
			this.fLabel139.Name = "fLabel139";
			this.fLabel139.Size = new Size(20, 20);
			this.fLabel139.TabIndex = 1;
			this.fLabel141.Cursor = Cursors.Hand;
			this.fLabel141.Ftype = FType.不等于;
			this.fLabel141.Margin = new Padding(5);
			this.fLabel141.Name = "fLabel141";
			this.fLabel141.Size = new Size(20, 20);
			this.fLabel141.TabIndex = 3;
			this.fLabel143.Cursor = Cursors.Hand;
			this.fLabel143.Ftype = FType.乘号;
			this.fLabel143.Margin = new Padding(5);
			this.fLabel143.Name = "fLabel143";
			this.fLabel143.Size = new Size(20, 20);
			this.fLabel143.TabIndex = 5;
			this.fLabel144.Cursor = Cursors.Hand;
			this.fLabel144.Ftype = FType.除号;
			this.fLabel144.Margin = new Padding(5);
			this.fLabel144.Name = "fLabel144";
			this.fLabel144.Size = new Size(20, 20);
			this.fLabel144.TabIndex = 6;
			this.fLabel145.Cursor = Cursors.Hand;
			this.fLabel145.Ftype = FType.阶乘号;
			this.fLabel145.Margin = new Padding(5);
			this.fLabel145.Name = "fLabel145";
			this.fLabel145.Size = new Size(20, 20);
			this.fLabel145.TabIndex = 7;
			this.fLabel146.Cursor = Cursors.Hand;
			this.fLabel146.Ftype = FType.成比例;
			this.fLabel146.Margin = new Padding(5);
			this.fLabel146.Name = "fLabel146";
			this.fLabel146.Size = new Size(20, 20);
			this.fLabel146.TabIndex = 8;
			this.fLabel148.Cursor = Cursors.Hand;
			this.fLabel148.Ftype = FType.远小于;
			this.fLabel148.Margin = new Padding(5);
			this.fLabel148.Name = "fLabel148";
			this.fLabel148.Size = new Size(20, 20);
			this.fLabel148.TabIndex = 10;
			this.fLabel150.Cursor = Cursors.Hand;
			this.fLabel150.Ftype = FType.远大于;
			this.fLabel150.Margin = new Padding(5);
			this.fLabel150.Name = "fLabel150";
			this.fLabel150.Size = new Size(20, 20);
			this.fLabel150.TabIndex = 12;
			this.fLabel151.Cursor = Cursors.Hand;
			this.fLabel151.Ftype = FType.小于等于;
			this.fLabel151.Margin = new Padding(5);
			this.fLabel151.Name = "fLabel151";
			this.fLabel151.Size = new Size(20, 20);
			this.fLabel151.TabIndex = 13;
			this.fLabel152.Cursor = Cursors.Hand;
			this.fLabel152.Ftype = FType.大于等于;
			this.fLabel152.Margin = new Padding(5);
			this.fLabel152.Name = "fLabel152";
			this.fLabel152.Size = new Size(20, 20);
			this.fLabel152.TabIndex = 14;
			this.fLabel153.Cursor = Cursors.Hand;
			this.fLabel153.Ftype = FType.减加号;
			this.fLabel153.Margin = new Padding(5);
			this.fLabel153.Name = "fLabel153";
			this.fLabel153.Size = new Size(20, 20);
			this.fLabel153.TabIndex = 15;
			this.fLabel154.Cursor = Cursors.Hand;
			this.fLabel154.Ftype = FType.约等于;
			this.fLabel154.Margin = new Padding(5);
			this.fLabel154.Name = "fLabel154";
			this.fLabel154.Size = new Size(20, 20);
			this.fLabel154.TabIndex = 16;
			this.fLabel155.Cursor = Cursors.Hand;
			this.fLabel155.Ftype = FType.几乎等于;
			this.fLabel155.Margin = new Padding(5);
			this.fLabel155.Name = "fLabel155";
			this.fLabel155.Size = new Size(20, 20);
			this.fLabel155.TabIndex = 17;
			this.fLabel156.Cursor = Cursors.Hand;
			this.fLabel156.Ftype = FType.等价于;
			this.fLabel156.Margin = new Padding(5);
			this.fLabel156.Name = "fLabel156";
			this.fLabel156.Size = new Size(20, 20);
			this.fLabel156.TabIndex = 18;
			this.fLabel157.Cursor = Cursors.Hand;
			this.fLabel157.Ftype = FType.任意;
			this.fLabel157.Margin = new Padding(5);
			this.fLabel157.Name = "fLabel157";
			this.fLabel157.Size = new Size(20, 20);
			this.fLabel157.TabIndex = 19;
			this.fLabel158.Cursor = Cursors.Hand;
			this.fLabel158.Ftype = FType.补集;
			this.fLabel158.Margin = new Padding(5);
			this.fLabel158.Name = "fLabel158";
			this.fLabel158.Size = new Size(20, 20);
			this.fLabel158.TabIndex = 20;
			this.fLabel159.Cursor = Cursors.Hand;
			this.fLabel159.Ftype = FType.偏微分;
			this.fLabel159.Margin = new Padding(5);
			this.fLabel159.Name = "fLabel159";
			this.fLabel159.Size = new Size(20, 20);
			this.fLabel159.TabIndex = 21;
			this.fLabel160.Cursor = Cursors.Hand;
			this.fLabel160.Ftype = FType.平方根号;
			this.fLabel160.Margin = new Padding(5);
			this.fLabel160.Name = "fLabel160";
			this.fLabel160.Size = new Size(20, 20);
			this.fLabel160.TabIndex = 22;
			this.fLabel161.Cursor = Cursors.Hand;
			this.fLabel161.Ftype = FType.立方根号;
			this.fLabel161.Margin = new Padding(5);
			this.fLabel161.Name = "fLabel161";
			this.fLabel161.Size = new Size(20, 20);
			this.fLabel161.TabIndex = 23;
			this.fLabel162.Cursor = Cursors.Hand;
			this.fLabel162.Ftype = FType.四方根号;
			this.fLabel162.Margin = new Padding(5);
			this.fLabel162.Name = "fLabel162";
			this.fLabel162.Size = new Size(20, 20);
			this.fLabel162.TabIndex = 24;
			this.fLabel163.Cursor = Cursors.Hand;
			this.fLabel163.Ftype = FType.并;
			this.fLabel163.Margin = new Padding(5);
			this.fLabel163.Name = "fLabel163";
			this.fLabel163.Size = new Size(20, 20);
			this.fLabel163.TabIndex = 25;
			this.fLabel164.Cursor = Cursors.Hand;
			this.fLabel164.Ftype = FType.交;
			this.fLabel164.Margin = new Padding(5);
			this.fLabel164.Name = "fLabel164";
			this.fLabel164.Size = new Size(20, 20);
			this.fLabel164.TabIndex = 26;
			this.fLabel165.Cursor = Cursors.Hand;
			this.fLabel165.Ftype = FType.空集;
			this.fLabel165.Margin = new Padding(5);
			this.fLabel165.Name = "fLabel165";
			this.fLabel165.Size = new Size(20, 20);
			this.fLabel165.TabIndex = 27;
			this.fLabel167.Cursor = Cursors.Hand;
			this.fLabel167.Ftype = FType.度;
			this.fLabel167.Margin = new Padding(5);
			this.fLabel167.Name = "fLabel167";
			this.fLabel167.Size = new Size(20, 20);
			this.fLabel167.TabIndex = 29;
			this.fLabel168.Cursor = Cursors.Hand;
			this.fLabel168.Ftype = FType.华氏度;
			this.fLabel168.Margin = new Padding(5);
			this.fLabel168.Name = "fLabel168";
			this.fLabel168.Size = new Size(20, 20);
			this.fLabel168.TabIndex = 30;
			this.fLabel169.Cursor = Cursors.Hand;
			this.fLabel169.Ftype = FType.摄氏度;
			this.fLabel169.Margin = new Padding(5);
			this.fLabel169.Name = "fLabel169";
			this.fLabel169.Size = new Size(20, 20);
			this.fLabel169.TabIndex = 31;
			this.fLabel170.Cursor = Cursors.Hand;
			this.fLabel170.Ftype = FType.递增;
			this.fLabel170.Margin = new Padding(5);
			this.fLabel170.Name = "fLabel170";
			this.fLabel170.Size = new Size(20, 20);
			this.fLabel170.TabIndex = 32;
			this.fLabel171.Cursor = Cursors.Hand;
			this.fLabel171.Ftype = FType.递减;
			this.fLabel171.Margin = new Padding(5);
			this.fLabel171.Name = "fLabel171";
			this.fLabel171.Size = new Size(20, 20);
			this.fLabel171.TabIndex = 33;
			this.fLabel172.Cursor = Cursors.Hand;
			this.fLabel172.Ftype = FType.存在;
			this.fLabel172.Margin = new Padding(5);
			this.fLabel172.Name = "fLabel172";
			this.fLabel172.Size = new Size(20, 20);
			this.fLabel172.TabIndex = 34;
			this.fLabel173.Cursor = Cursors.Hand;
			this.fLabel173.Ftype = FType.不存在;
			this.fLabel173.Margin = new Padding(5);
			this.fLabel173.Name = "fLabel173";
			this.fLabel173.Size = new Size(20, 20);
			this.fLabel173.TabIndex = 35;
			this.fLabel174.Cursor = Cursors.Hand;
			this.fLabel174.Ftype = FType.属于;
			this.fLabel174.Margin = new Padding(5);
			this.fLabel174.Name = "fLabel174";
			this.fLabel174.Size = new Size(20, 20);
			this.fLabel174.TabIndex = 36;
			this.fLabel175.Cursor = Cursors.Hand;
			this.fLabel175.Ftype = FType.属于于;
			this.fLabel175.Margin = new Padding(5);
			this.fLabel175.Name = "fLabel175";
			this.fLabel175.Size = new Size(20, 20);
			this.fLabel175.TabIndex = 37;
			this.fLabel176.Cursor = Cursors.Hand;
			this.fLabel176.Ftype = FType.左箭头;
			this.fLabel176.Margin = new Padding(5);
			this.fLabel176.Name = "fLabel176";
			this.fLabel176.Size = new Size(20, 20);
			this.fLabel176.TabIndex = 38;
			this.fLabel177.Cursor = Cursors.Hand;
			this.fLabel177.Ftype = FType.上箭头;
			this.fLabel177.Margin = new Padding(5);
			this.fLabel177.Name = "fLabel177";
			this.fLabel177.Size = new Size(20, 20);
			this.fLabel177.TabIndex = 39;
			this.fLabel178.Cursor = Cursors.Hand;
			this.fLabel178.Ftype = FType.下箭头;
			this.fLabel178.Margin = new Padding(5);
			this.fLabel178.Name = "fLabel178";
			this.fLabel178.Size = new Size(20, 20);
			this.fLabel178.TabIndex = 40;
			this.fLabel179.Cursor = Cursors.Hand;
			this.fLabel179.Ftype = FType.右箭头;
			this.fLabel179.Margin = new Padding(5);
			this.fLabel179.Name = "fLabel179";
			this.fLabel179.Size = new Size(20, 20);
			this.fLabel179.TabIndex = 41;
			this.fLabel180.Cursor = Cursors.Hand;
			this.fLabel180.Ftype = FType.双向箭头;
			this.fLabel180.Margin = new Padding(5);
			this.fLabel180.Name = "fLabel180";
			this.fLabel180.Size = new Size(20, 20);
			this.fLabel180.TabIndex = 42;
			this.fLabel181.Cursor = Cursors.Hand;
			this.fLabel181.Ftype = FType.因为;
			this.fLabel181.Margin = new Padding(5);
			this.fLabel181.Name = "fLabel181";
			this.fLabel181.Size = new Size(20, 20);
			this.fLabel181.TabIndex = 43;
			this.fLabel182.Cursor = Cursors.Hand;
			this.fLabel182.Ftype = FType.所以;
			this.fLabel182.Margin = new Padding(5);
			this.fLabel182.Name = "fLabel182";
			this.fLabel182.Size = new Size(20, 20);
			this.fLabel182.TabIndex = 44;
			this.fLabel185.Cursor = Cursors.Hand;
			this.fLabel185.Ftype = FType.未签名;
			this.fLabel185.Margin = new Padding(5);
			this.fLabel185.Name = "fLabel185";
			this.fLabel185.Size = new Size(20, 20);
			this.fLabel185.TabIndex = 47;
			this.fLabel186.Cursor = Cursors.Hand;
			this.fLabel186.Ftype = FType.希腊1;
			this.fLabel186.Margin = new Padding(5);
			this.fLabel186.Name = "fLabel186";
			this.fLabel186.Size = new Size(20, 20);
			this.fLabel186.TabIndex = 48;
			this.fLabel187.Cursor = Cursors.Hand;
			this.fLabel187.Ftype = FType.希腊2;
			this.fLabel187.Margin = new Padding(5);
			this.fLabel187.Name = "fLabel187";
			this.fLabel187.Size = new Size(20, 20);
			this.fLabel187.TabIndex = 49;
			this.fLabel188.Cursor = Cursors.Hand;
			this.fLabel188.Ftype = FType.希腊3;
			this.fLabel188.Margin = new Padding(5);
			this.fLabel188.Name = "fLabel188";
			this.fLabel188.Size = new Size(20, 20);
			this.fLabel188.TabIndex = 50;
			this.fLabel189.Cursor = Cursors.Hand;
			this.fLabel189.Ftype = FType.希腊4;
			this.fLabel189.Margin = new Padding(5);
			this.fLabel189.Name = "fLabel189";
			this.fLabel189.Size = new Size(20, 20);
			this.fLabel189.TabIndex = 51;
			this.fLabel190.Cursor = Cursors.Hand;
			this.fLabel190.Ftype = FType.希腊5;
			this.fLabel190.Margin = new Padding(5);
			this.fLabel190.Name = "fLabel190";
			this.fLabel190.Size = new Size(20, 20);
			this.fLabel190.TabIndex = 52;
			this.fLabel191.Cursor = Cursors.Hand;
			this.fLabel191.Ftype = FType.希腊6;
			this.fLabel191.Margin = new Padding(5);
			this.fLabel191.Name = "fLabel191";
			this.fLabel191.Size = new Size(20, 20);
			this.fLabel191.TabIndex = 53;
			this.fLabel192.Cursor = Cursors.Hand;
			this.fLabel192.Ftype = FType.希腊7;
			this.fLabel192.Margin = new Padding(5);
			this.fLabel192.Name = "fLabel192";
			this.fLabel192.Size = new Size(20, 20);
			this.fLabel192.TabIndex = 54;
			this.fLabel193.Cursor = Cursors.Hand;
			this.fLabel193.Ftype = FType.希腊8;
			this.fLabel193.Margin = new Padding(5);
			this.fLabel193.Name = "fLabel193";
			this.fLabel193.Size = new Size(20, 20);
			this.fLabel193.TabIndex = 55;
			this.fLabel194.Cursor = Cursors.Hand;
			this.fLabel194.Ftype = FType.希腊9;
			this.fLabel194.Margin = new Padding(5);
			this.fLabel194.Name = "fLabel194";
			this.fLabel194.Size = new Size(20, 20);
			this.fLabel194.TabIndex = 56;
			this.fLabel195.Cursor = Cursors.Hand;
			this.fLabel195.Ftype = FType.希腊10;
			this.fLabel195.Margin = new Padding(5);
			this.fLabel195.Name = "fLabel195";
			this.fLabel195.Size = new Size(20, 20);
			this.fLabel195.TabIndex = 57;
			this.fLabel196.Cursor = Cursors.Hand;
			this.fLabel196.Ftype = FType.希腊11;
			this.fLabel196.Margin = new Padding(5);
			this.fLabel196.Name = "fLabel196";
			this.fLabel196.Size = new Size(20, 20);
			this.fLabel196.TabIndex = 58;
			this.fLabel197.Cursor = Cursors.Hand;
			this.fLabel197.Ftype = FType.希腊12;
			this.fLabel197.Margin = new Padding(5);
			this.fLabel197.Name = "fLabel197";
			this.fLabel197.Size = new Size(20, 20);
			this.fLabel197.TabIndex = 59;
			this.fLabel198.Cursor = Cursors.Hand;
			this.fLabel198.Ftype = FType.希腊13;
			this.fLabel198.Margin = new Padding(5);
			this.fLabel198.Name = "fLabel198";
			this.fLabel198.Size = new Size(20, 20);
			this.fLabel198.TabIndex = 60;
			this.fLabel199.Cursor = Cursors.Hand;
			this.fLabel199.Ftype = FType.希腊14;
			this.fLabel199.Margin = new Padding(5);
			this.fLabel199.Name = "fLabel199";
			this.fLabel199.Size = new Size(20, 20);
			this.fLabel199.TabIndex = 61;
			this.fLabel200.Cursor = Cursors.Hand;
			this.fLabel200.Ftype = FType.希腊15;
			this.fLabel200.Margin = new Padding(5);
			this.fLabel200.Name = "fLabel200";
			this.fLabel200.Size = new Size(20, 20);
			this.fLabel200.TabIndex = 62;
			this.fLabel201.Cursor = Cursors.Hand;
			this.fLabel201.Ftype = FType.星乘;
			this.fLabel201.Margin = new Padding(5);
			this.fLabel201.Name = "fLabel201";
			this.fLabel201.Size = new Size(20, 20);
			this.fLabel201.TabIndex = 63;
			this.fLabel202.Cursor = Cursors.Hand;
			this.fLabel202.Ftype = FType.着重点;
			this.fLabel202.Margin = new Padding(5);
			this.fLabel202.Name = "fLabel202";
			this.fLabel202.Size = new Size(20, 20);
			this.fLabel202.TabIndex = 64;
			this.fLabel203.Cursor = Cursors.Hand;
			this.fLabel203.Ftype = FType.垂直省略号;
			this.fLabel203.Margin = new Padding(5);
			this.fLabel203.Name = "fLabel203";
			this.fLabel203.Size = new Size(20, 20);
			this.fLabel203.TabIndex = 65;
			this.fLabel204.Cursor = Cursors.Hand;
			this.fLabel204.Ftype = FType.中间水平省略号;
			this.fLabel204.Margin = new Padding(5);
			this.fLabel204.Name = "fLabel204";
			this.fLabel204.Size = new Size(20, 20);
			this.fLabel204.TabIndex = 66;
			this.fLabel205.Cursor = Cursors.Hand;
			this.fLabel205.Ftype = FType.右上对角省略号;
			this.fLabel205.Margin = new Padding(5);
			this.fLabel205.Name = "fLabel205";
			this.fLabel205.Size = new Size(20, 20);
			this.fLabel205.TabIndex = 67;
			this.fLabel206.Cursor = Cursors.Hand;
			this.fLabel206.Ftype = FType.右下对角省略号;
			this.fLabel206.Margin = new Padding(5);
			this.fLabel206.Name = "fLabel206";
			this.fLabel206.Size = new Size(20, 20);
			this.fLabel206.TabIndex = 68;
			this.fLabel207.Cursor = Cursors.Hand;
			this.fLabel207.Ftype = FType.希腊16;
			this.fLabel207.Margin = new Padding(5);
			this.fLabel207.Name = "fLabel207";
			this.fLabel207.Size = new Size(20, 20);
			this.fLabel207.TabIndex = 69;
			this.fLabel208.Cursor = Cursors.Hand;
			this.fLabel208.Ftype = FType.希腊17;
			this.fLabel208.Margin = new Padding(5);
			this.fLabel208.Name = "fLabel208";
			this.fLabel208.Size = new Size(20, 20);
			this.fLabel208.TabIndex = 70;
			this.fLabel209.Cursor = Cursors.Hand;
			this.fLabel209.Ftype = FType.直角;
			this.fLabel209.Margin = new Padding(5);
			this.fLabel209.Name = "fLabel209";
			this.fLabel209.Size = new Size(20, 20);
			this.fLabel209.TabIndex = 71;
			this.fLabel210.Cursor = Cursors.Hand;
			this.fLabel210.Ftype = FType.角度;
			this.fLabel210.Margin = new Padding(5);
			this.fLabel210.Name = "fLabel210";
			this.fLabel210.Size = new Size(20, 20);
			this.fLabel210.TabIndex = 72;
			this.fLabel211.Cursor = Cursors.Hand;
			this.fLabel211.Ftype = FType.测量角;
			this.fLabel211.Margin = new Padding(5);
			this.fLabel211.Name = "fLabel211";
			this.fLabel211.Size = new Size(20, 20);
			this.fLabel211.TabIndex = 73;
			this.fLabel212.Cursor = Cursors.Hand;
			this.fLabel212.Ftype = FType.球面角;
			this.fLabel212.Margin = new Padding(5);
			this.fLabel212.Name = "fLabel212";
			this.fLabel212.Size = new Size(20, 20);
			this.fLabel212.TabIndex = 74;
			this.fLabel213.Cursor = Cursors.Hand;
			this.fLabel213.Ftype = FType.以弧度表示的直角;
			this.fLabel213.Margin = new Padding(5);
			this.fLabel213.Name = "fLabel213";
			this.fLabel213.Size = new Size(20, 20);
			this.fLabel213.TabIndex = 75;
			this.fLabel214.Cursor = Cursors.Hand;
			this.fLabel214.Ftype = FType.直角三角形;
			this.fLabel214.Margin = new Padding(5);
			this.fLabel214.Name = "fLabel214";
			this.fLabel214.Size = new Size(20, 20);
			this.fLabel214.TabIndex = 76;
			this.fLabel215.Cursor = Cursors.Hand;
			this.fLabel215.Ftype = FType.等于且平行于;
			this.fLabel215.Margin = new Padding(5);
			this.fLabel215.Name = "fLabel215";
			this.fLabel215.Size = new Size(20, 20);
			this.fLabel215.TabIndex = 77;
			this.fLabel216.Cursor = Cursors.Hand;
			this.fLabel216.Ftype = FType.垂直于;
			this.fLabel216.Margin = new Padding(5);
			this.fLabel216.Name = "fLabel216";
			this.fLabel216.Size = new Size(20, 20);
			this.fLabel216.TabIndex = 78;
			this.fLabel217.Cursor = Cursors.Hand;
			this.fLabel217.Ftype = FType.不整除;
			this.fLabel217.Margin = new Padding(5);
			this.fLabel217.Name = "fLabel217";
			this.fLabel217.Size = new Size(20, 20);
			this.fLabel217.TabIndex = 79;
			this.fLabel218.Cursor = Cursors.Hand;
			this.fLabel218.Ftype = FType.平行于;
			this.fLabel218.Margin = new Padding(5);
			this.fLabel218.Name = "fLabel218";
			this.fLabel218.Size = new Size(20, 20);
			this.fLabel218.TabIndex = 80;
			this.fLabel219.Cursor = Cursors.Hand;
			this.fLabel219.Ftype = FType.不平行于;
			this.fLabel219.Margin = new Padding(5);
			this.fLabel219.Name = "fLabel219";
			this.fLabel219.Size = new Size(20, 20);
			this.fLabel219.TabIndex = 81;
			this.fLabel220.Cursor = Cursors.Hand;
			this.fLabel220.Ftype = FType.比率;
			this.fLabel220.Margin = new Padding(5);
			this.fLabel220.Name = "fLabel220";
			this.fLabel220.Size = new Size(20, 20);
			this.fLabel220.TabIndex = 82;
			this.fLabel221.Cursor = Cursors.Hand;
			this.fLabel221.Ftype = FType.比例;
			this.fLabel221.Margin = new Padding(5);
			this.fLabel221.Name = "fLabel221";
			this.fLabel221.Size = new Size(20, 20);
			this.fLabel221.TabIndex = 83;
			this.fLabel3.Cursor = Cursors.Hand;
			this.fLabel3.Ftype = FType.上标;
			this.fLabel3.Margin = new Padding(5);
			this.fLabel3.Name = "fLabel3";
			this.fLabel3.Size = new Size(30, 30);
			this.fLabel3.TabIndex = 2;
			this.fLabel4.Cursor = Cursors.Hand;
			this.fLabel4.Ftype = FType.下标;
			this.fLabel4.Margin = new Padding(5);
			this.fLabel4.Name = "fLabel4";
			this.fLabel4.Size = new Size(30, 30);
			this.fLabel4.TabIndex = 3;
			this.fLabel6.Cursor = Cursors.Hand;
			this.fLabel6.Ftype = FType.上下标右;
			this.fLabel6.Margin = new Padding(5);
			this.fLabel6.Name = "fLabel6";
			this.fLabel6.Size = new Size(30, 30);
			this.fLabel6.TabIndex = 5;
			this.fLabel5.Cursor = Cursors.Hand;
			this.fLabel5.Ftype = FType.上下标左;
			this.fLabel5.Margin = new Padding(5);
			this.fLabel5.Name = "fLabel5";
			this.fLabel5.Size = new Size(30, 30);
			this.fLabel5.TabIndex = 4;
			this.fLabel7.Cursor = Cursors.Hand;
			this.fLabel7.Ftype = FType.平方根;
			this.fLabel7.Margin = new Padding(5);
			this.fLabel7.Name = "fLabel7";
			this.fLabel7.Size = new Size(30, 30);
			this.fLabel7.TabIndex = 6;
			this.fLabel8.Cursor = Cursors.Hand;
			this.fLabel8.Ftype = FType.立方根;
			this.fLabel8.Margin = new Padding(5);
			this.fLabel8.Name = "fLabel8";
			this.fLabel8.Size = new Size(30, 30);
			this.fLabel8.TabIndex = 7;
			this.fLabel9.Cursor = Cursors.Hand;
			this.fLabel9.Ftype = FType.一般根式;
			this.fLabel9.Margin = new Padding(5);
			this.fLabel9.Name = "fLabel9";
			this.fLabel9.Size = new Size(30, 30);
			this.fLabel9.TabIndex = 8;
			this.fLabel10.Cursor = Cursors.Hand;
			this.fLabel10.Ftype = FType.积分1;
			this.fLabel10.Margin = new Padding(5);
			this.fLabel10.Name = "fLabel10";
			this.fLabel10.Size = new Size(30, 30);
			this.fLabel10.TabIndex = 9;
			this.fLabel23.Cursor = Cursors.Hand;
			this.fLabel23.Ftype = FType.积分2;
			this.fLabel23.Margin = new Padding(5);
			this.fLabel23.Name = "fLabel23";
			this.fLabel23.Size = new Size(30, 30);
			this.fLabel23.TabIndex = 22;
			this.fLabel36.Cursor = Cursors.Hand;
			this.fLabel36.Ftype = FType.积分3;
			this.fLabel36.Margin = new Padding(5);
			this.fLabel36.Name = "fLabel36";
			this.fLabel36.Size = new Size(30, 30);
			this.fLabel36.TabIndex = 35;
			this.fLabel13.Cursor = Cursors.Hand;
			this.fLabel13.Ftype = FType.二重积分1;
			this.fLabel13.Margin = new Padding(5);
			this.fLabel13.Name = "fLabel13";
			this.fLabel13.Size = new Size(30, 30);
			this.fLabel13.TabIndex = 12;
			this.fLabel24.Cursor = Cursors.Hand;
			this.fLabel24.Ftype = FType.二重积分2;
			this.fLabel24.Margin = new Padding(5);
			this.fLabel24.Name = "fLabel24";
			this.fLabel24.Size = new Size(30, 30);
			this.fLabel24.TabIndex = 23;
			this.fLabel37.Cursor = Cursors.Hand;
			this.fLabel37.Ftype = FType.二重积分3;
			this.fLabel37.Margin = new Padding(5);
			this.fLabel37.Name = "fLabel37";
			this.fLabel37.Size = new Size(30, 30);
			this.fLabel37.TabIndex = 36;
			this.fLabel14.Cursor = Cursors.Hand;
			this.fLabel14.Ftype = FType.三重积分1;
			this.fLabel14.Margin = new Padding(5);
			this.fLabel14.Name = "fLabel14";
			this.fLabel14.Size = new Size(30, 30);
			this.fLabel14.TabIndex = 13;
			this.fLabel25.Cursor = Cursors.Hand;
			this.fLabel25.Ftype = FType.三重积分2;
			this.fLabel25.Margin = new Padding(5);
			this.fLabel25.Name = "fLabel25";
			this.fLabel25.Size = new Size(30, 30);
			this.fLabel25.TabIndex = 24;
			this.fLabel38.Cursor = Cursors.Hand;
			this.fLabel38.Ftype = FType.三重积分3;
			this.fLabel38.Margin = new Padding(5);
			this.fLabel38.Name = "fLabel38";
			this.fLabel38.Size = new Size(30, 30);
			this.fLabel38.TabIndex = 37;
			this.fLabel11.Cursor = Cursors.Hand;
			this.fLabel11.Ftype = FType.围道积分1;
			this.fLabel11.Margin = new Padding(5);
			this.fLabel11.Name = "fLabel11";
			this.fLabel11.Size = new Size(30, 30);
			this.fLabel11.TabIndex = 10;
			this.fLabel27.Cursor = Cursors.Hand;
			this.fLabel27.Ftype = FType.围道积分2;
			this.fLabel27.Margin = new Padding(5);
			this.fLabel27.Name = "fLabel27";
			this.fLabel27.Size = new Size(30, 30);
			this.fLabel27.TabIndex = 26;
			this.fLabel39.Cursor = Cursors.Hand;
			this.fLabel39.Ftype = FType.围道积分3;
			this.fLabel39.Margin = new Padding(5);
			this.fLabel39.Name = "fLabel39";
			this.fLabel39.Size = new Size(30, 30);
			this.fLabel39.TabIndex = 38;
			this.fLabel12.Cursor = Cursors.Hand;
			this.fLabel12.Ftype = FType.面积分1;
			this.fLabel12.Margin = new Padding(5);
			this.fLabel12.Name = "fLabel12";
			this.fLabel12.Size = new Size(30, 30);
			this.fLabel12.TabIndex = 11;
			this.fLabel28.Cursor = Cursors.Hand;
			this.fLabel28.Ftype = FType.面积分2;
			this.fLabel28.Margin = new Padding(5);
			this.fLabel28.Name = "fLabel28";
			this.fLabel28.Size = new Size(30, 30);
			this.fLabel28.TabIndex = 27;
			this.fLabel40.Cursor = Cursors.Hand;
			this.fLabel40.Ftype = FType.面积分3;
			this.fLabel40.Margin = new Padding(5);
			this.fLabel40.Name = "fLabel40";
			this.fLabel40.Size = new Size(30, 30);
			this.fLabel40.TabIndex = 39;
			this.fLabel15.Cursor = Cursors.Hand;
			this.fLabel15.Ftype = FType.体积分1;
			this.fLabel15.Margin = new Padding(5);
			this.fLabel15.Name = "fLabel15";
			this.fLabel15.Size = new Size(30, 30);
			this.fLabel15.TabIndex = 14;
			this.fLabel29.Cursor = Cursors.Hand;
			this.fLabel29.Ftype = FType.体积分2;
			this.fLabel29.Margin = new Padding(5);
			this.fLabel29.Name = "fLabel29";
			this.fLabel29.Size = new Size(30, 30);
			this.fLabel29.TabIndex = 28;
			this.fLabel41.Cursor = Cursors.Hand;
			this.fLabel41.Ftype = FType.体积分3;
			this.fLabel41.Margin = new Padding(5);
			this.fLabel41.Name = "fLabel41";
			this.fLabel41.Size = new Size(30, 30);
			this.fLabel41.TabIndex = 40;
			this.fLabel16.Cursor = Cursors.Hand;
			this.fLabel16.Ftype = FType.求和1;
			this.fLabel16.Margin = new Padding(5);
			this.fLabel16.Name = "fLabel16";
			this.fLabel16.Size = new Size(30, 30);
			this.fLabel16.TabIndex = 15;
			this.fLabel26.Cursor = Cursors.Hand;
			this.fLabel26.Ftype = FType.求和2;
			this.fLabel26.Margin = new Padding(5);
			this.fLabel26.Name = "fLabel26";
			this.fLabel26.Size = new Size(30, 30);
			this.fLabel26.TabIndex = 25;
			this.fLabel43.Cursor = Cursors.Hand;
			this.fLabel43.Ftype = FType.求和3;
			this.fLabel43.Margin = new Padding(5);
			this.fLabel43.Name = "fLabel43";
			this.fLabel43.Size = new Size(30, 30);
			this.fLabel43.TabIndex = 42;
			this.fLabel49.Cursor = Cursors.Hand;
			this.fLabel49.Ftype = FType.求和4;
			this.fLabel49.Margin = new Padding(5);
			this.fLabel49.Name = "fLabel49";
			this.fLabel49.Size = new Size(30, 30);
			this.fLabel49.TabIndex = 48;
			this.fLabel56.Cursor = Cursors.Hand;
			this.fLabel56.Ftype = FType.求和5;
			this.fLabel56.Margin = new Padding(5);
			this.fLabel56.Name = "fLabel56";
			this.fLabel56.Size = new Size(30, 30);
			this.fLabel56.TabIndex = 55;
			this.fLabel17.Cursor = Cursors.Hand;
			this.fLabel17.Ftype = FType.乘积1;
			this.fLabel17.Margin = new Padding(5);
			this.fLabel17.Name = "fLabel17";
			this.fLabel17.Size = new Size(30, 30);
			this.fLabel17.TabIndex = 16;
			this.fLabel30.Cursor = Cursors.Hand;
			this.fLabel30.Ftype = FType.乘积2;
			this.fLabel30.Margin = new Padding(5);
			this.fLabel30.Name = "fLabel30";
			this.fLabel30.Size = new Size(30, 30);
			this.fLabel30.TabIndex = 29;
			this.fLabel44.Cursor = Cursors.Hand;
			this.fLabel44.Ftype = FType.乘积2;
			this.fLabel44.Margin = new Padding(5);
			this.fLabel44.Name = "fLabel44";
			this.fLabel44.Size = new Size(30, 30);
			this.fLabel44.TabIndex = 43;
			this.fLabel50.Cursor = Cursors.Hand;
			this.fLabel50.Ftype = FType.乘积4;
			this.fLabel50.Margin = new Padding(5);
			this.fLabel50.Name = "fLabel50";
			this.fLabel50.Size = new Size(30, 30);
			this.fLabel50.TabIndex = 49;
			this.fLabel57.Cursor = Cursors.Hand;
			this.fLabel57.Ftype = FType.乘积5;
			this.fLabel57.Margin = new Padding(5);
			this.fLabel57.Name = "fLabel57";
			this.fLabel57.Size = new Size(30, 30);
			this.fLabel57.TabIndex = 56;
			this.fLabel18.Cursor = Cursors.Hand;
			this.fLabel18.Ftype = FType.副积1;
			this.fLabel18.Margin = new Padding(5);
			this.fLabel18.Name = "fLabel18";
			this.fLabel18.Size = new Size(30, 30);
			this.fLabel18.TabIndex = 17;
			this.fLabel31.Cursor = Cursors.Hand;
			this.fLabel31.Ftype = FType.副积2;
			this.fLabel31.Margin = new Padding(5);
			this.fLabel31.Name = "fLabel31";
			this.fLabel31.Size = new Size(30, 30);
			this.fLabel31.TabIndex = 30;
			this.fLabel45.Cursor = Cursors.Hand;
			this.fLabel45.Ftype = FType.副积3;
			this.fLabel45.Margin = new Padding(5);
			this.fLabel45.Name = "fLabel45";
			this.fLabel45.Size = new Size(30, 30);
			this.fLabel45.TabIndex = 44;
			this.fLabel51.Cursor = Cursors.Hand;
			this.fLabel51.Ftype = FType.副积4;
			this.fLabel51.Margin = new Padding(5);
			this.fLabel51.Name = "fLabel51";
			this.fLabel51.Size = new Size(30, 30);
			this.fLabel51.TabIndex = 50;
			this.fLabel58.Cursor = Cursors.Hand;
			this.fLabel58.Ftype = FType.副积5;
			this.fLabel58.Margin = new Padding(5);
			this.fLabel58.Name = "fLabel58";
			this.fLabel58.Size = new Size(30, 30);
			this.fLabel58.TabIndex = 57;
			this.fLabel19.Cursor = Cursors.Hand;
			this.fLabel19.Ftype = FType.并11;
			this.fLabel19.Margin = new Padding(5);
			this.fLabel19.Name = "fLabel19";
			this.fLabel19.Size = new Size(30, 30);
			this.fLabel19.TabIndex = 18;
			this.fLabel32.Cursor = Cursors.Hand;
			this.fLabel32.Ftype = FType.并12;
			this.fLabel32.Margin = new Padding(5);
			this.fLabel32.Name = "fLabel32";
			this.fLabel32.Size = new Size(30, 30);
			this.fLabel32.TabIndex = 31;
			this.fLabel42.Cursor = Cursors.Hand;
			this.fLabel42.Ftype = FType.并13;
			this.fLabel42.Margin = new Padding(5);
			this.fLabel42.Name = "fLabel42";
			this.fLabel42.Size = new Size(30, 30);
			this.fLabel42.TabIndex = 41;
			this.fLabel52.Cursor = Cursors.Hand;
			this.fLabel52.Ftype = FType.并14;
			this.fLabel52.Margin = new Padding(5);
			this.fLabel52.Name = "fLabel52";
			this.fLabel52.Size = new Size(30, 30);
			this.fLabel52.TabIndex = 51;
			this.fLabel59.Cursor = Cursors.Hand;
			this.fLabel59.Ftype = FType.并15;
			this.fLabel59.Margin = new Padding(5);
			this.fLabel59.Name = "fLabel59";
			this.fLabel59.Size = new Size(30, 30);
			this.fLabel59.TabIndex = 58;
			this.fLabel20.Cursor = Cursors.Hand;
			this.fLabel20.Ftype = FType.交11;
			this.fLabel20.Margin = new Padding(5);
			this.fLabel20.Name = "fLabel20";
			this.fLabel20.Size = new Size(30, 30);
			this.fLabel20.TabIndex = 19;
			this.fLabel33.Cursor = Cursors.Hand;
			this.fLabel33.Ftype = FType.交12;
			this.fLabel33.Margin = new Padding(5);
			this.fLabel33.Name = "fLabel33";
			this.fLabel33.Size = new Size(30, 30);
			this.fLabel33.TabIndex = 32;
			this.fLabel46.Cursor = Cursors.Hand;
			this.fLabel46.Ftype = FType.交13;
			this.fLabel46.Margin = new Padding(5);
			this.fLabel46.Name = "fLabel46";
			this.fLabel46.Size = new Size(30, 30);
			this.fLabel46.TabIndex = 45;
			this.fLabel53.Cursor = Cursors.Hand;
			this.fLabel53.Ftype = FType.交14;
			this.fLabel53.Margin = new Padding(5);
			this.fLabel53.Name = "fLabel53";
			this.fLabel53.Size = new Size(30, 30);
			this.fLabel53.TabIndex = 52;
			this.fLabel60.Cursor = Cursors.Hand;
			this.fLabel60.Ftype = FType.交15;
			this.fLabel60.Margin = new Padding(5);
			this.fLabel60.Name = "fLabel60";
			this.fLabel60.Size = new Size(30, 30);
			this.fLabel60.TabIndex = 59;
			this.fLabel21.Cursor = Cursors.Hand;
			this.fLabel21.Ftype = FType.并21;
			this.fLabel21.Margin = new Padding(5);
			this.fLabel21.Name = "fLabel21";
			this.fLabel21.Size = new Size(30, 30);
			this.fLabel21.TabIndex = 20;
			this.fLabel34.Cursor = Cursors.Hand;
			this.fLabel34.Ftype = FType.并22;
			this.fLabel34.Margin = new Padding(5);
			this.fLabel34.Name = "fLabel34";
			this.fLabel34.Size = new Size(30, 30);
			this.fLabel34.TabIndex = 33;
			this.fLabel47.Cursor = Cursors.Hand;
			this.fLabel47.Ftype = FType.并23;
			this.fLabel47.Margin = new Padding(5);
			this.fLabel47.Name = "fLabel47";
			this.fLabel47.Size = new Size(30, 30);
			this.fLabel47.TabIndex = 46;
			this.fLabel54.Cursor = Cursors.Hand;
			this.fLabel54.Ftype = FType.并24;
			this.fLabel54.Margin = new Padding(5);
			this.fLabel54.Name = "fLabel54";
			this.fLabel54.Size = new Size(30, 30);
			this.fLabel54.TabIndex = 53;
			this.fLabel61.Cursor = Cursors.Hand;
			this.fLabel61.Ftype = FType.并25;
			this.fLabel61.Margin = new Padding(5);
			this.fLabel61.Name = "fLabel61";
			this.fLabel61.Size = new Size(30, 30);
			this.fLabel61.TabIndex = 60;
			this.fLabel22.Cursor = Cursors.Hand;
			this.fLabel22.Ftype = FType.交21;
			this.fLabel22.Margin = new Padding(5);
			this.fLabel22.Name = "fLabel22";
			this.fLabel22.Size = new Size(30, 30);
			this.fLabel22.TabIndex = 21;
			this.fLabel35.Cursor = Cursors.Hand;
			this.fLabel35.Ftype = FType.交22;
			this.fLabel35.Margin = new Padding(5);
			this.fLabel35.Name = "fLabel35";
			this.fLabel35.Size = new Size(30, 30);
			this.fLabel35.TabIndex = 34;
			this.fLabel48.Cursor = Cursors.Hand;
			this.fLabel48.Ftype = FType.交23;
			this.fLabel48.Margin = new Padding(5);
			this.fLabel48.Name = "fLabel48";
			this.fLabel48.Size = new Size(30, 30);
			this.fLabel48.TabIndex = 47;
			this.fLabel55.Cursor = Cursors.Hand;
			this.fLabel55.Ftype = FType.交24;
			this.fLabel55.Margin = new Padding(5);
			this.fLabel55.Name = "fLabel55";
			this.fLabel55.Size = new Size(30, 30);
			this.fLabel55.TabIndex = 54;
			this.fLabel62.Cursor = Cursors.Hand;
			this.fLabel62.Ftype = FType.交25;
			this.fLabel62.Margin = new Padding(5);
			this.fLabel62.Name = "fLabel62";
			this.fLabel62.Size = new Size(30, 30);
			this.fLabel62.TabIndex = 61;
			this.fLabel63.Cursor = Cursors.Hand;
			this.fLabel63.Ftype = FType.正弦;
			this.fLabel63.Margin = new Padding(5);
			this.fLabel63.Name = "fLabel63";
			this.fLabel63.Size = new Size(30, 30);
			this.fLabel63.TabIndex = 62;
			this.fLabel78.Cursor = Cursors.Hand;
			this.fLabel78.Ftype = FType.正弦_2;
			this.fLabel78.Margin = new Padding(5);
			this.fLabel78.Name = "fLabel78";
			this.fLabel78.Size = new Size(30, 30);
			this.fLabel78.TabIndex = 77;
			this.fLabel64.Cursor = Cursors.Hand;
			this.fLabel64.Ftype = FType.余弦;
			this.fLabel64.Margin = new Padding(5);
			this.fLabel64.Name = "fLabel64";
			this.fLabel64.Size = new Size(30, 30);
			this.fLabel64.TabIndex = 63;
			this.fLabel79.Cursor = Cursors.Hand;
			this.fLabel79.Ftype = FType.余弦_2;
			this.fLabel79.Margin = new Padding(5);
			this.fLabel79.Name = "fLabel79";
			this.fLabel79.Size = new Size(30, 30);
			this.fLabel79.TabIndex = 78;
			this.fLabel65.Cursor = Cursors.Hand;
			this.fLabel65.Ftype = FType.正切;
			this.fLabel65.Margin = new Padding(5);
			this.fLabel65.Name = "fLabel65";
			this.fLabel65.Size = new Size(30, 30);
			this.fLabel65.TabIndex = 64;
			this.fLabel80.Cursor = Cursors.Hand;
			this.fLabel80.Ftype = FType.正切_2;
			this.fLabel80.Margin = new Padding(5);
			this.fLabel80.Name = "fLabel80";
			this.fLabel80.Size = new Size(30, 30);
			this.fLabel80.TabIndex = 79;
			this.fLabel66.Cursor = Cursors.Hand;
			this.fLabel66.Ftype = FType.余切;
			this.fLabel66.Margin = new Padding(5);
			this.fLabel66.Name = "fLabel66";
			this.fLabel66.Size = new Size(30, 30);
			this.fLabel66.TabIndex = 65;
			this.fLabel81.Cursor = Cursors.Hand;
			this.fLabel81.Ftype = FType.余切_2;
			this.fLabel81.Margin = new Padding(5);
			this.fLabel81.Name = "fLabel81";
			this.fLabel81.Size = new Size(30, 30);
			this.fLabel81.TabIndex = 80;
			this.fLabel67.Cursor = Cursors.Hand;
			this.fLabel67.Ftype = FType.余割;
			this.fLabel67.Margin = new Padding(5);
			this.fLabel67.Name = "fLabel67";
			this.fLabel67.Size = new Size(30, 30);
			this.fLabel67.TabIndex = 66;
			this.fLabel82.Cursor = Cursors.Hand;
			this.fLabel82.Ftype = FType.余割_2;
			this.fLabel82.Margin = new Padding(5);
			this.fLabel82.Name = "fLabel82";
			this.fLabel82.Size = new Size(30, 30);
			this.fLabel82.TabIndex = 81;
			this.fLabel68.Cursor = Cursors.Hand;
			this.fLabel68.Ftype = FType.正割;
			this.fLabel68.Margin = new Padding(5);
			this.fLabel68.Name = "fLabel68";
			this.fLabel68.Size = new Size(30, 30);
			this.fLabel68.TabIndex = 67;
			this.fLabel83.Cursor = Cursors.Hand;
			this.fLabel83.Ftype = FType.正割_2;
			this.fLabel83.Margin = new Padding(5);
			this.fLabel83.Name = "fLabel83";
			this.fLabel83.Size = new Size(30, 30);
			this.fLabel83.TabIndex = 82;
			this.fLabel69.Cursor = Cursors.Hand;
			this.fLabel69.Ftype = FType.双曲正弦;
			this.fLabel69.Margin = new Padding(5);
			this.fLabel69.Name = "fLabel69";
			this.fLabel69.Size = new Size(30, 30);
			this.fLabel69.TabIndex = 68;
			this.fLabel84.Cursor = Cursors.Hand;
			this.fLabel84.Ftype = FType.双曲正弦_2;
			this.fLabel84.Margin = new Padding(5);
			this.fLabel84.Name = "fLabel84";
			this.fLabel84.Size = new Size(30, 30);
			this.fLabel84.TabIndex = 83;
			this.fLabel70.Cursor = Cursors.Hand;
			this.fLabel70.Ftype = FType.双曲余弦;
			this.fLabel70.Margin = new Padding(5);
			this.fLabel70.Name = "fLabel70";
			this.fLabel70.Size = new Size(30, 30);
			this.fLabel70.TabIndex = 69;
			this.fLabel85.Cursor = Cursors.Hand;
			this.fLabel85.Ftype = FType.双曲余弦_2;
			this.fLabel85.Margin = new Padding(5);
			this.fLabel85.Name = "fLabel85";
			this.fLabel85.Size = new Size(30, 30);
			this.fLabel85.TabIndex = 84;
			this.fLabel71.Cursor = Cursors.Hand;
			this.fLabel71.Ftype = FType.双曲正切;
			this.fLabel71.Margin = new Padding(5);
			this.fLabel71.Name = "fLabel71";
			this.fLabel71.Size = new Size(30, 30);
			this.fLabel71.TabIndex = 70;
			this.fLabel86.Cursor = Cursors.Hand;
			this.fLabel86.Ftype = FType.双曲正切_2;
			this.fLabel86.Margin = new Padding(5);
			this.fLabel86.Name = "fLabel86";
			this.fLabel86.Size = new Size(30, 30);
			this.fLabel86.TabIndex = 85;
			this.fLabel72.Cursor = Cursors.Hand;
			this.fLabel72.Ftype = FType.双曲余切;
			this.fLabel72.Margin = new Padding(5);
			this.fLabel72.Name = "fLabel72";
			this.fLabel72.Size = new Size(30, 30);
			this.fLabel72.TabIndex = 71;
			this.fLabel87.Cursor = Cursors.Hand;
			this.fLabel87.Ftype = FType.双曲余切_2;
			this.fLabel87.Margin = new Padding(5);
			this.fLabel87.Name = "fLabel87";
			this.fLabel87.Size = new Size(30, 30);
			this.fLabel87.TabIndex = 86;
			this.fLabel73.Cursor = Cursors.Hand;
			this.fLabel73.Ftype = FType.双曲余割;
			this.fLabel73.Margin = new Padding(5);
			this.fLabel73.Name = "fLabel73";
			this.fLabel73.Size = new Size(30, 30);
			this.fLabel73.TabIndex = 72;
			this.fLabel88.Cursor = Cursors.Hand;
			this.fLabel88.Ftype = FType.双曲余割_2;
			this.fLabel88.Margin = new Padding(5);
			this.fLabel88.Name = "fLabel88";
			this.fLabel88.Size = new Size(30, 30);
			this.fLabel88.TabIndex = 87;
			this.fLabel74.Cursor = Cursors.Hand;
			this.fLabel74.Ftype = FType.双曲正割;
			this.fLabel74.Margin = new Padding(5);
			this.fLabel74.Name = "fLabel74";
			this.fLabel74.Size = new Size(30, 30);
			this.fLabel74.TabIndex = 73;
			this.fLabel89.Cursor = Cursors.Hand;
			this.fLabel89.Ftype = FType.双曲正割_2;
			this.fLabel89.Margin = new Padding(5);
			this.fLabel89.Name = "fLabel89";
			this.fLabel89.Size = new Size(30, 30);
			this.fLabel89.TabIndex = 88;
			this.fLabel75.Cursor = Cursors.Hand;
			this.fLabel75.Ftype = FType.对数2;
			this.fLabel75.Margin = new Padding(5);
			this.fLabel75.Name = "fLabel75";
			this.fLabel75.Size = new Size(30, 30);
			this.fLabel75.TabIndex = 74;
			this.fLabel76.Cursor = Cursors.Hand;
			this.fLabel76.Ftype = FType.对数e;
			this.fLabel76.Margin = new Padding(5);
			this.fLabel76.Name = "fLabel76";
			this.fLabel76.Size = new Size(30, 30);
			this.fLabel76.TabIndex = 75;
			this.fLabel77.Cursor = Cursors.Hand;
			this.fLabel77.Ftype = FType.对数10;
			this.fLabel77.Margin = new Padding(5);
			this.fLabel77.Name = "fLabel77";
			this.fLabel77.Size = new Size(30, 30);
			this.fLabel77.TabIndex = 76;
			this.fLabel90.Cursor = Cursors.Hand;
			this.fLabel90.Ftype = FType.对数;
			this.fLabel90.Margin = new Padding(5);
			this.fLabel90.Name = "fLabel90";
			this.fLabel90.Size = new Size(30, 30);
			this.fLabel90.TabIndex = 89;
			this.fLabel91.Cursor = Cursors.Hand;
			this.fLabel91.Ftype = FType.极限;
			this.fLabel91.Margin = new Padding(5);
			this.fLabel91.Name = "fLabel91";
			this.fLabel91.Size = new Size(30, 30);
			this.fLabel91.TabIndex = 90;
			this.fLabel92.Cursor = Cursors.Hand;
			this.fLabel92.Ftype = FType.最大值;
			this.fLabel92.Margin = new Padding(5);
			this.fLabel92.Name = "fLabel92";
			this.fLabel92.Size = new Size(30, 30);
			this.fLabel92.TabIndex = 91;
			this.fLabel93.Cursor = Cursors.Hand;
			this.fLabel93.Ftype = FType.最小值;
			this.fLabel93.Margin = new Padding(5);
			this.fLabel93.Name = "fLabel93";
			this.fLabel93.Size = new Size(30, 30);
			this.fLabel93.TabIndex = 92;
			this.fLabel94.Cursor = Cursors.Hand;
			this.fLabel94.Ftype = FType.点;
			this.fLabel94.Margin = new Padding(5);
			this.fLabel94.Name = "fLabel94";
			this.fLabel94.Size = new Size(30, 30);
			this.fLabel94.TabIndex = 93;
			this.fLabel95.Cursor = Cursors.Hand;
			this.fLabel95.Ftype = FType.双点;
			this.fLabel95.Margin = new Padding(5);
			this.fLabel95.Name = "fLabel95";
			this.fLabel95.Size = new Size(30, 30);
			this.fLabel95.TabIndex = 94;
			this.fLabel96.Cursor = Cursors.Hand;
			this.fLabel96.Ftype = FType.三点;
			this.fLabel96.Margin = new Padding(5);
			this.fLabel96.Name = "fLabel96";
			this.fLabel96.Size = new Size(30, 30);
			this.fLabel96.TabIndex = 95;
			this.fLabel97.Cursor = Cursors.Hand;
			this.fLabel97.Ftype = FType.乘幂号;
			this.fLabel97.Margin = new Padding(5);
			this.fLabel97.Name = "fLabel97";
			this.fLabel97.Size = new Size(30, 30);
			this.fLabel97.TabIndex = 96;
			this.fLabel98.Cursor = Cursors.Hand;
			this.fLabel98.Ftype = FType.对号;
			this.fLabel98.Margin = new Padding(5);
			this.fLabel98.Name = "fLabel98";
			this.fLabel98.Size = new Size(30, 30);
			this.fLabel98.TabIndex = 97;
			this.fLabel99.Cursor = Cursors.Hand;
			this.fLabel99.Ftype = FType.尖音符号;
			this.fLabel99.Margin = new Padding(5);
			this.fLabel99.Name = "fLabel99";
			this.fLabel99.Size = new Size(30, 30);
			this.fLabel99.TabIndex = 98;
			this.fLabel100.Cursor = Cursors.Hand;
			this.fLabel100.Ftype = FType.抑音符号;
			this.fLabel100.Margin = new Padding(5);
			this.fLabel100.Name = "fLabel100";
			this.fLabel100.Size = new Size(30, 30);
			this.fLabel100.TabIndex = 99;
			this.fLabel101.Cursor = Cursors.Hand;
			this.fLabel101.Ftype = FType.短音符号;
			this.fLabel101.Margin = new Padding(5);
			this.fLabel101.Name = "fLabel101";
			this.fLabel101.Size = new Size(30, 30);
			this.fLabel101.TabIndex = 100;
			this.fLabel102.Cursor = Cursors.Hand;
			this.fLabel102.Ftype = FType.颚化符;
			this.fLabel102.Margin = new Padding(5);
			this.fLabel102.Name = "fLabel102";
			this.fLabel102.Size = new Size(30, 30);
			this.fLabel102.TabIndex = 101;
			this.fLabel103.Cursor = Cursors.Hand;
			this.fLabel103.Ftype = FType.横杠;
			this.fLabel103.Margin = new Padding(5);
			this.fLabel103.Name = "fLabel103";
			this.fLabel103.Size = new Size(30, 30);
			this.fLabel103.TabIndex = 102;
			this.fLabel104.Cursor = Cursors.Hand;
			this.fLabel104.Ftype = FType.双顶线;
			this.fLabel104.Margin = new Padding(5);
			this.fLabel104.Name = "fLabel104";
			this.fLabel104.Size = new Size(30, 30);
			this.fLabel104.TabIndex = 103;
			this.fLabel105.Cursor = Cursors.Hand;
			this.fLabel105.Ftype = FType.带框公式;
			this.fLabel105.Margin = new Padding(5);
			this.fLabel105.Name = "fLabel105";
			this.fLabel105.Size = new Size(30, 30);
			this.fLabel105.TabIndex = 104;
			this.fLabel106.Cursor = Cursors.Hand;
			this.fLabel106.Ftype = FType.上方大括号;
			this.fLabel106.Margin = new Padding(5);
			this.fLabel106.Name = "fLabel106";
			this.fLabel106.Size = new Size(30, 30);
			this.fLabel106.TabIndex = 105;
			this.fLabel107.Cursor = Cursors.Hand;
			this.fLabel107.Ftype = FType.下方大括号;
			this.fLabel107.Margin = new Padding(5);
			this.fLabel107.Name = "fLabel107";
			this.fLabel107.Size = new Size(30, 30);
			this.fLabel107.TabIndex = 106;
			this.fLabel108.Cursor = Cursors.Hand;
			this.fLabel108.Ftype = FType.分组字符在上;
			this.fLabel108.Margin = new Padding(5);
			this.fLabel108.Name = "fLabel108";
			this.fLabel108.Size = new Size(30, 30);
			this.fLabel108.TabIndex = 107;
			this.fLabel109.Cursor = Cursors.Hand;
			this.fLabel109.Ftype = FType.分组字符在下;
			this.fLabel109.Margin = new Padding(5);
			this.fLabel109.Name = "fLabel109";
			this.fLabel109.Size = new Size(30, 30);
			this.fLabel109.TabIndex = 108;
			this.fLabel110.Cursor = Cursors.Hand;
			this.fLabel110.Ftype = FType.左箭头在上;
			this.fLabel110.Margin = new Padding(5);
			this.fLabel110.Name = "fLabel110";
			this.fLabel110.Size = new Size(30, 30);
			this.fLabel110.TabIndex = 109;
			this.fLabel111.Cursor = Cursors.Hand;
			this.fLabel111.Ftype = FType.右箭头在上;
			this.fLabel111.Margin = new Padding(5);
			this.fLabel111.Name = "fLabel111";
			this.fLabel111.Size = new Size(30, 30);
			this.fLabel111.TabIndex = 110;
			this.fLabel112.Cursor = Cursors.Hand;
			this.fLabel112.Ftype = FType.双向箭头在上;
			this.fLabel112.Margin = new Padding(5);
			this.fLabel112.Name = "fLabel112";
			this.fLabel112.Size = new Size(30, 30);
			this.fLabel112.TabIndex = 111;
			this.fLabel113.Cursor = Cursors.Hand;
			this.fLabel113.Ftype = FType.右向简式箭头在上;
			this.fLabel113.Margin = new Padding(5);
			this.fLabel113.Name = "fLabel113";
			this.fLabel113.Size = new Size(30, 30);
			this.fLabel113.TabIndex = 112;
			this.fLabel114.Cursor = Cursors.Hand;
			this.fLabel114.Ftype = FType.左向简式箭头在上;
			this.fLabel114.Margin = new Padding(5);
			this.fLabel114.Name = "fLabel114";
			this.fLabel114.Size = new Size(30, 30);
			this.fLabel114.TabIndex = 113;
			this.fLabel115.Cursor = Cursors.Hand;
			this.fLabel115.Ftype = FType.大括号;
			this.fLabel115.Margin = new Padding(5);
			this.fLabel115.Name = "fLabel115";
			this.fLabel115.Size = new Size(30, 30);
			this.fLabel115.TabIndex = 114;
			this.fLabel116.Cursor = Cursors.Hand;
			this.fLabel116.Ftype = FType.方括号;
			this.fLabel116.Margin = new Padding(5);
			this.fLabel116.Name = "fLabel116";
			this.fLabel116.Size = new Size(30, 30);
			this.fLabel116.TabIndex = 115;
			this.fLabel117.Cursor = Cursors.Hand;
			this.fLabel117.Ftype = FType.括号;
			this.fLabel117.Margin = new Padding(5);
			this.fLabel117.Name = "fLabel117";
			this.fLabel117.Size = new Size(30, 30);
			this.fLabel117.TabIndex = 116;
			this.fLabel118.Cursor = Cursors.Hand;
			this.fLabel118.Ftype = FType.尖括号;
			this.fLabel118.Margin = new Padding(5);
			this.fLabel118.Name = "fLabel118";
			this.fLabel118.Size = new Size(30, 30);
			this.fLabel118.TabIndex = 117;
			this.fLabel119.Cursor = Cursors.Hand;
			this.fLabel119.Ftype = FType.绝对值1;
			this.fLabel119.Margin = new Padding(5);
			this.fLabel119.Name = "fLabel119";
			this.fLabel119.Size = new Size(30, 30);
			this.fLabel119.TabIndex = 118;
			this.fLabel120.Cursor = Cursors.Hand;
			this.fLabel120.Ftype = FType.绝对值2;
			this.fLabel120.Margin = new Padding(5);
			this.fLabel120.Name = "fLabel120";
			this.fLabel120.Size = new Size(30, 30);
			this.fLabel120.TabIndex = 119;
			this.fLabel121.Cursor = Cursors.Hand;
			this.fLabel121.Ftype = FType.中间水平省略号;
			this.fLabel121.Margin = new Padding(5);
			this.fLabel121.Name = "fLabel121";
			this.fLabel121.Size = new Size(30, 30);
			this.fLabel121.TabIndex = 120;
			this.fLabel122.Cursor = Cursors.Hand;
			this.fLabel122.Ftype = FType.垂直省略号;
			this.fLabel122.Margin = new Padding(5);
			this.fLabel122.Name = "fLabel122";
			this.fLabel122.Size = new Size(30, 30);
			this.fLabel122.TabIndex = 121;
			this.fLabel123.Cursor = Cursors.Hand;
			this.fLabel123.Ftype = FType.右下对角省略号;
			this.fLabel123.Margin = new Padding(5);
			this.fLabel123.Name = "fLabel123";
			this.fLabel123.Size = new Size(30, 30);
			this.fLabel123.TabIndex = 122;
			this.fLabel124.Cursor = Cursors.Hand;
			this.fLabel124.Ftype = FType.单边大括号;
			this.fLabel124.Margin = new Padding(5);
			this.fLabel124.Name = "fLabel124";
			this.fLabel124.Size = new Size(30, 30);
			this.fLabel124.TabIndex = 123;
			this.fLabel125.Cursor = Cursors.Hand;
			this.fLabel125.Ftype = FType.等号1;
			this.fLabel125.Margin = new Padding(5);
			this.fLabel125.Name = "fLabel125";
			this.fLabel125.Size = new Size(30, 30);
			this.fLabel125.TabIndex = 124;
			this.fLabel129.Cursor = Cursors.Hand;
			this.fLabel129.Ftype = FType.等号2;
			this.fLabel129.Margin = new Padding(5);
			this.fLabel129.Name = "fLabel129";
			this.fLabel129.Size = new Size(30, 30);
			this.fLabel129.TabIndex = 128;
			this.fLabel130.Cursor = Cursors.Hand;
			this.fLabel130.Ftype = FType.等号3;
			this.fLabel130.Margin = new Padding(5);
			this.fLabel130.Name = "fLabel130";
			this.fLabel130.Size = new Size(30, 30);
			this.fLabel130.TabIndex = 129;
			this.fLabel126.Cursor = Cursors.Hand;
			this.fLabel126.Ftype = FType.左箭头1;
			this.fLabel126.Margin = new Padding(5);
			this.fLabel126.Name = "fLabel126";
			this.fLabel126.Size = new Size(30, 30);
			this.fLabel126.TabIndex = 125;
			this.fLabel131.Cursor = Cursors.Hand;
			this.fLabel131.Ftype = FType.左箭头2;
			this.fLabel131.Margin = new Padding(5);
			this.fLabel131.Name = "fLabel131";
			this.fLabel131.Size = new Size(30, 30);
			this.fLabel131.TabIndex = 130;
			this.fLabel132.Cursor = Cursors.Hand;
			this.fLabel132.Ftype = FType.左箭头3;
			this.fLabel132.Margin = new Padding(5);
			this.fLabel132.Name = "fLabel132";
			this.fLabel132.Size = new Size(30, 30);
			this.fLabel132.TabIndex = 131;
			this.fLabel127.Cursor = Cursors.Hand;
			this.fLabel127.Ftype = FType.右箭头1;
			this.fLabel127.Margin = new Padding(5);
			this.fLabel127.Name = "fLabel127";
			this.fLabel127.Size = new Size(30, 30);
			this.fLabel127.TabIndex = 126;
			this.fLabel133.Cursor = Cursors.Hand;
			this.fLabel133.Ftype = FType.右箭头2;
			this.fLabel133.Margin = new Padding(5);
			this.fLabel133.Name = "fLabel133";
			this.fLabel133.Size = new Size(30, 30);
			this.fLabel133.TabIndex = 132;
			this.fLabel134.Cursor = Cursors.Hand;
			this.fLabel134.Ftype = FType.右箭头3;
			this.fLabel134.Margin = new Padding(5);
			this.fLabel134.Name = "fLabel134";
			this.fLabel134.Size = new Size(30, 30);
			this.fLabel134.TabIndex = 133;
			this.fLabel128.Cursor = Cursors.Hand;
			this.fLabel128.Ftype = FType.双向箭头1;
			this.fLabel128.Margin = new Padding(5);
			this.fLabel128.Name = "fLabel128";
			this.fLabel128.Size = new Size(30, 30);
			this.fLabel128.TabIndex = 127;
			this.fLabel135.Cursor = Cursors.Hand;
			this.fLabel135.Ftype = FType.双向箭头2;
			this.fLabel135.Margin = new Padding(5);
			this.fLabel135.Name = "fLabel135";
			this.fLabel135.Size = new Size(30, 30);
			this.fLabel135.TabIndex = 134;
			this.fLabel136.Cursor = Cursors.Hand;
			this.fLabel136.Ftype = FType.双向箭头3;
			this.fLabel136.Margin = new Padding(5);
			this.fLabel136.Name = "fLabel136";
			this.fLabel136.Size = new Size(30, 30);
			this.fLabel136.TabIndex = 135;
			this.fLabel137.Cursor = Cursors.Hand;
			this.fLabel137.Ftype = FType.矩阵;
			this.fLabel137.Margin = new Padding(5);
			this.fLabel137.Name = "fLabel137";
			this.fLabel137.Size = new Size(30, 30);
			this.fLabel137.TabIndex = 136;
			this.FLabelLists[0].Add(this.fLabel138);
			this.FLabelLists[0].Add(this.fLabel139);
			this.FLabelLists[0].Add(this.fLabel141);
			this.FLabelLists[0].Add(this.fLabel143);
			this.FLabelLists[0].Add(this.fLabel144);
			this.FLabelLists[0].Add(this.fLabel145);
			this.FLabelLists[0].Add(this.fLabel146);
			this.FLabelLists[0].Add(this.fLabel148);
			this.FLabelLists[0].Add(this.fLabel150);
			this.FLabelLists[0].Add(this.fLabel151);
			this.FLabelLists[0].Add(this.fLabel152);
			this.FLabelLists[0].Add(this.fLabel153);
			this.FLabelLists[0].Add(this.fLabel154);
			this.FLabelLists[0].Add(this.fLabel155);
			this.FLabelLists[0].Add(this.fLabel156);
			this.FLabelLists[0].Add(this.fLabel157);
			this.FLabelLists[0].Add(this.fLabel158);
			this.FLabelLists[0].Add(this.fLabel159);
			this.FLabelLists[0].Add(this.fLabel160);
			this.FLabelLists[0].Add(this.fLabel161);
			this.FLabelLists[0].Add(this.fLabel162);
			this.FLabelLists[0].Add(this.fLabel163);
			this.FLabelLists[0].Add(this.fLabel164);
			this.FLabelLists[0].Add(this.fLabel165);
			this.FLabelLists[0].Add(this.fLabel167);
			this.FLabelLists[0].Add(this.fLabel168);
			this.FLabelLists[0].Add(this.fLabel169);
			this.FLabelLists[0].Add(this.fLabel170);
			this.FLabelLists[0].Add(this.fLabel171);
			this.FLabelLists[0].Add(this.fLabel172);
			this.FLabelLists[0].Add(this.fLabel173);
			this.FLabelLists[0].Add(this.fLabel174);
			this.FLabelLists[0].Add(this.fLabel175);
			this.FLabelLists[0].Add(this.fLabel176);
			this.FLabelLists[0].Add(this.fLabel177);
			this.FLabelLists[0].Add(this.fLabel178);
			this.FLabelLists[0].Add(this.fLabel179);
			this.FLabelLists[0].Add(this.fLabel180);
			this.FLabelLists[0].Add(this.fLabel181);
			this.FLabelLists[0].Add(this.fLabel182);
			this.FLabelLists[0].Add(this.fLabel185);
			this.FLabelLists[0].Add(this.fLabel186);
			this.FLabelLists[0].Add(this.fLabel187);
			this.FLabelLists[0].Add(this.fLabel188);
			this.FLabelLists[0].Add(this.fLabel189);
			this.FLabelLists[0].Add(this.fLabel190);
			this.FLabelLists[0].Add(this.fLabel191);
			this.FLabelLists[0].Add(this.fLabel192);
			this.FLabelLists[0].Add(this.fLabel193);
			this.FLabelLists[0].Add(this.fLabel194);
			this.FLabelLists[0].Add(this.fLabel195);
			this.FLabelLists[0].Add(this.fLabel196);
			this.FLabelLists[0].Add(this.fLabel197);
			this.FLabelLists[0].Add(this.fLabel198);
			this.FLabelLists[0].Add(this.fLabel199);
			this.FLabelLists[0].Add(this.fLabel200);
			this.FLabelLists[0].Add(this.fLabel201);
			this.FLabelLists[0].Add(this.fLabel202);
			this.FLabelLists[0].Add(this.fLabel203);
			this.FLabelLists[0].Add(this.fLabel204);
			this.FLabelLists[0].Add(this.fLabel205);
			this.FLabelLists[0].Add(this.fLabel206);
			this.FLabelLists[0].Add(this.fLabel207);
			this.FLabelLists[0].Add(this.fLabel208);
			this.FLabelLists[0].Add(this.fLabel209);
			this.FLabelLists[0].Add(this.fLabel210);
			this.FLabelLists[0].Add(this.fLabel211);
			this.FLabelLists[0].Add(this.fLabel212);
			this.FLabelLists[0].Add(this.fLabel213);
			this.FLabelLists[0].Add(this.fLabel214);
			this.FLabelLists[0].Add(this.fLabel215);
			this.FLabelLists[0].Add(this.fLabel216);
			this.FLabelLists[0].Add(this.fLabel217);
			this.FLabelLists[0].Add(this.fLabel218);
			this.FLabelLists[0].Add(this.fLabel219);
			this.FLabelLists[0].Add(this.fLabel220);
			this.FLabelLists[0].Add(this.fLabel221);
			this.FLabelLists[1].Add(this.fLabel1);
			this.FLabelLists[1].Add(this.fLabel2);
			this.FLabelLists[2].Add(this.fLabel3);
			this.FLabelLists[2].Add(this.fLabel4);
			this.FLabelLists[2].Add(this.fLabel6);
			this.FLabelLists[2].Add(this.fLabel5);
			this.FLabelLists[3].Add(this.fLabel7);
			this.FLabelLists[3].Add(this.fLabel8);
			this.FLabelLists[3].Add(this.fLabel9);
			this.FLabelLists[4].Add(this.fLabel10);
			this.FLabelLists[4].Add(this.fLabel23);
			this.FLabelLists[4].Add(this.fLabel36);
			this.FLabelLists[4].Add(this.fLabel13);
			this.FLabelLists[4].Add(this.fLabel24);
			this.FLabelLists[4].Add(this.fLabel37);
			this.FLabelLists[4].Add(this.fLabel14);
			this.FLabelLists[4].Add(this.fLabel25);
			this.FLabelLists[4].Add(this.fLabel38);
			this.FLabelLists[4].Add(this.fLabel11);
			this.FLabelLists[4].Add(this.fLabel27);
			this.FLabelLists[4].Add(this.fLabel39);
			this.FLabelLists[4].Add(this.fLabel12);
			this.FLabelLists[4].Add(this.fLabel28);
			this.FLabelLists[4].Add(this.fLabel40);
			this.FLabelLists[4].Add(this.fLabel15);
			this.FLabelLists[4].Add(this.fLabel29);
			this.FLabelLists[4].Add(this.fLabel41);
			this.FLabelLists[5].Add(this.fLabel16);
			this.FLabelLists[5].Add(this.fLabel26);
			this.FLabelLists[5].Add(this.fLabel43);
			this.FLabelLists[5].Add(this.fLabel49);
			this.FLabelLists[5].Add(this.fLabel56);
			this.FLabelLists[5].Add(this.fLabel17);
			this.FLabelLists[5].Add(this.fLabel30);
			this.FLabelLists[5].Add(this.fLabel44);
			this.FLabelLists[5].Add(this.fLabel50);
			this.FLabelLists[5].Add(this.fLabel57);
			this.FLabelLists[5].Add(this.fLabel18);
			this.FLabelLists[5].Add(this.fLabel31);
			this.FLabelLists[5].Add(this.fLabel45);
			this.FLabelLists[5].Add(this.fLabel51);
			this.FLabelLists[5].Add(this.fLabel58);
			this.FLabelLists[5].Add(this.fLabel19);
			this.FLabelLists[5].Add(this.fLabel32);
			this.FLabelLists[5].Add(this.fLabel42);
			this.FLabelLists[5].Add(this.fLabel52);
			this.FLabelLists[5].Add(this.fLabel59);
			this.FLabelLists[5].Add(this.fLabel20);
			this.FLabelLists[5].Add(this.fLabel33);
			this.FLabelLists[5].Add(this.fLabel46);
			this.FLabelLists[5].Add(this.fLabel53);
			this.FLabelLists[5].Add(this.fLabel60);
			this.FLabelLists[5].Add(this.fLabel21);
			this.FLabelLists[5].Add(this.fLabel34);
			this.FLabelLists[5].Add(this.fLabel47);
			this.FLabelLists[5].Add(this.fLabel54);
			this.FLabelLists[5].Add(this.fLabel61);
			this.FLabelLists[5].Add(this.fLabel22);
			this.FLabelLists[5].Add(this.fLabel35);
			this.FLabelLists[5].Add(this.fLabel48);
			this.FLabelLists[5].Add(this.fLabel55);
			this.FLabelLists[5].Add(this.fLabel62);
			this.FLabelLists[7].Add(this.fLabel63);
			this.FLabelLists[7].Add(this.fLabel78);
			this.FLabelLists[7].Add(this.fLabel64);
			this.FLabelLists[7].Add(this.fLabel79);
			this.FLabelLists[7].Add(this.fLabel65);
			this.FLabelLists[7].Add(this.fLabel80);
			this.FLabelLists[7].Add(this.fLabel66);
			this.FLabelLists[7].Add(this.fLabel81);
			this.FLabelLists[7].Add(this.fLabel67);
			this.FLabelLists[7].Add(this.fLabel82);
			this.FLabelLists[7].Add(this.fLabel68);
			this.FLabelLists[7].Add(this.fLabel83);
			this.FLabelLists[7].Add(this.fLabel69);
			this.FLabelLists[7].Add(this.fLabel84);
			this.FLabelLists[7].Add(this.fLabel70);
			this.FLabelLists[7].Add(this.fLabel85);
			this.FLabelLists[7].Add(this.fLabel71);
			this.FLabelLists[7].Add(this.fLabel86);
			this.FLabelLists[7].Add(this.fLabel72);
			this.FLabelLists[7].Add(this.fLabel87);
			this.FLabelLists[7].Add(this.fLabel73);
			this.FLabelLists[7].Add(this.fLabel88);
			this.FLabelLists[7].Add(this.fLabel74);
			this.FLabelLists[7].Add(this.fLabel89);
			this.FLabelLists[9].Add(this.fLabel75);
			this.FLabelLists[9].Add(this.fLabel76);
			this.FLabelLists[9].Add(this.fLabel77);
			this.FLabelLists[9].Add(this.fLabel90);
			this.FLabelLists[9].Add(this.fLabel91);
			this.FLabelLists[9].Add(this.fLabel92);
			this.FLabelLists[9].Add(this.fLabel93);
			this.FLabelLists[8].Add(this.fLabel94);
			this.FLabelLists[8].Add(this.fLabel95);
			this.FLabelLists[8].Add(this.fLabel96);
			this.FLabelLists[8].Add(this.fLabel97);
			this.FLabelLists[8].Add(this.fLabel98);
			this.FLabelLists[8].Add(this.fLabel99);
			this.FLabelLists[8].Add(this.fLabel100);
			this.FLabelLists[8].Add(this.fLabel101);
			this.FLabelLists[8].Add(this.fLabel102);
			this.FLabelLists[8].Add(this.fLabel103);
			this.FLabelLists[8].Add(this.fLabel104);
			this.FLabelLists[8].Add(this.fLabel105);
			this.FLabelLists[8].Add(this.fLabel106);
			this.FLabelLists[8].Add(this.fLabel107);
			this.FLabelLists[8].Add(this.fLabel108);
			this.FLabelLists[8].Add(this.fLabel109);
			this.FLabelLists[8].Add(this.fLabel110);
			this.FLabelLists[8].Add(this.fLabel111);
			this.FLabelLists[8].Add(this.fLabel112);
			this.FLabelLists[8].Add(this.fLabel113);
			this.FLabelLists[8].Add(this.fLabel114);
			this.FLabelLists[6].Add(this.fLabel115);
			this.FLabelLists[6].Add(this.fLabel116);
			this.FLabelLists[6].Add(this.fLabel117);
			this.FLabelLists[6].Add(this.fLabel118);
			this.FLabelLists[6].Add(this.fLabel119);
			this.FLabelLists[6].Add(this.fLabel120);
			this.FLabelLists[11].Add(this.fLabel121);
			this.FLabelLists[11].Add(this.fLabel122);
			this.FLabelLists[11].Add(this.fLabel123);
			this.FLabelLists[6].Add(this.fLabel124);
			this.FLabelLists[10].Add(this.fLabel125);
			this.FLabelLists[10].Add(this.fLabel129);
			this.FLabelLists[10].Add(this.fLabel130);
			this.FLabelLists[10].Add(this.fLabel126);
			this.FLabelLists[10].Add(this.fLabel131);
			this.FLabelLists[10].Add(this.fLabel132);
			this.FLabelLists[10].Add(this.fLabel127);
			this.FLabelLists[10].Add(this.fLabel133);
			this.FLabelLists[10].Add(this.fLabel134);
			this.FLabelLists[10].Add(this.fLabel128);
			this.FLabelLists[10].Add(this.fLabel135);
			this.FLabelLists[10].Add(this.fLabel136);
			this.FLabelLists[11].Add(this.fLabel137);
			for (int i = 0; i < this.FlowLayoutPanels.Length; i++)
			{
				this.FlowLayoutPanels[i] = new FlowLayoutPanel();
				this.FlowLayoutPanels[i].AutoSize = false;
				this.FlowLayoutPanels[i].BorderStyle = BorderStyle.FixedSingle;
				this.FlowLayoutPanels[i].AutoScroll = true;
				this.FlowLayoutPanels[i].AutoSize = true;
				this.FlowLayoutPanels[i].AutoSizeMode = AutoSizeMode.GrowAndShrink;
				this.FlowLayoutPanels[i].Size = new Size(300, 600);
				foreach (FLabel current in this.FLabelLists[i])
				{
					this.FlowLayoutPanels[i].Controls.Add(current);
				}
			}
			int verticalScrollBarWidth = SystemInformation.VerticalScrollBarWidth;
			int horizontalScrollBarHeight = SystemInformation.HorizontalScrollBarHeight;
			Size borderSize = SystemInformation.BorderSize;
			this.FlowLayoutPanels[0].Size = new Size(this.flowLayoutPanel2.Width, 400);
			this.FlowLayoutPanels[1].Size = new Size(80 + borderSize.Width * 2, 40 + borderSize.Height * 2);
			this.FlowLayoutPanels[2].Size = new Size(160 + borderSize.Width * 2, 40 + borderSize.Height * 2);
			this.FlowLayoutPanels[3].Size = new Size(120 + borderSize.Width * 2, 40 + borderSize.Height * 2);
			this.FlowLayoutPanels[4].Size = new Size(120 + borderSize.Width * 2 + verticalScrollBarWidth, 120 + borderSize.Height * 2);
			this.FlowLayoutPanels[5].Size = new Size(200 + borderSize.Width * 2 + verticalScrollBarWidth, 120 + borderSize.Height * 2);
			this.FlowLayoutPanels[6].Size = new Size(160 + borderSize.Width * 2, 80 + borderSize.Height * 2);
			this.FlowLayoutPanels[7].Size = new Size(240 + borderSize.Width * 2 + verticalScrollBarWidth, 120 + borderSize.Height * 2);
			this.FlowLayoutPanels[8].Size = new Size(120 + borderSize.Width * 2 + verticalScrollBarWidth, 120 + borderSize.Height * 2);
			this.FlowLayoutPanels[9].Size = new Size(160 + borderSize.Width * 2 + verticalScrollBarWidth, 80 + borderSize.Height * 2);
			this.FlowLayoutPanels[10].Size = new Size(120 + borderSize.Width * 2 + verticalScrollBarWidth, 120 + borderSize.Height * 2);
			this.FlowLayoutPanels[11].Size = new Size(160 + borderSize.Width * 2, 40 + borderSize.Height * 2);
			int num = 0;
			int num2 = 0;
			foreach (FLabel current in this.FLabelLists[0])
			{
				if (num == 0)
				{
					num2++;
				}
				num++;
				this.flowLayoutPanel2.Controls.Add(current);
				FLabel fLabel = new FLabel(current.Ftype, false);
				fLabel.Size = current.Size;
				fLabel.Padding = current.Padding;
				this.FlowLayoutPanels[0].Controls.Add(fLabel);
				fLabel.AppendExpression += new FLabel.AppendExpressionHandler(this.f_AppenExpression);
				if (this.flowLayoutPanel2.ClientSize.Width - num * 30 - borderSize.Width * 2 < verticalScrollBarWidth + 30)
				{
					num = 0;
					this.flowLayoutPanel2.SetFlowBreak(current, true);
					this.FlowLayoutPanels[0].SetFlowBreak(fLabel, true);
				}
			}
			this.FlowLayoutPanels[0].Height = 30 * num2 + borderSize.Height * 2;
			this.flowLayoutPanel2.AutoScroll = true;
			this.flowLayoutPanel2.Scroll += new ScrollEventHandler(this.flowLayoutPanel2_Scroll);
			for (int i = 0; i < 12; i++)
			{
				this.PopupHosts.Add(new PopupHost(this.FlowLayoutPanels[i]));
				this.PopupHosts[i].AutoClose = true;
				this.PopupHosts[i].Closed += new ToolStripDropDownClosedEventHandler(this.FormulaEditor_Closed);
			}
			List<FLabel>[] fLabelLists = this.FLabelLists;
			for (int j = 0; j < fLabelLists.Length; j++)
			{
				List<FLabel> list = fLabelLists[j];
				foreach (FLabel current in list)
				{
					current.AppendExpression += new FLabel.AppendExpressionHandler(this.f_AppenExpression);
				}
			}
			try
			{
				this.id1 = 100;
				NativeMethods.RegisterHotKey(base.Handle, this.id1, NativeMethods.KeyModifiers.Alt, Keys.F);
			}
			catch
			{
			}
			try
			{
				this.id2 = this.id1 + 1;
				NativeMethods.RegisterHotKey(base.Handle, this.id2, NativeMethods.KeyModifiers.Alt, Keys.S);
			}
			catch
			{
			}
			try
			{
				this.id3 = this.id2 + 1;
				NativeMethods.RegisterHotKey(base.Handle, this.id3, NativeMethods.KeyModifiers.Alt, Keys.X);
			}
			catch
			{
			}
		}
		private void f_AppenExpression(object sender, ExpressionEventArgs e)
		{
			Form form = base.FindForm();
			if (form != null && form.ActiveControl != null)
			{
				if (form.ActiveControl.GetType().ToString() == "Qisi.Editor.Controls.SuperBox")
				{
					((SuperBox)form.ActiveControl).AppendF(e.Type);
				}
				else
				{
					Control control = this.ActiveSuperBox(form.ActiveControl);
					if (control != null)
					{
						((SuperBox)control).AppendF(e.Type);
					}
				}
			}
			if (sender.GetType().ToString() == "Qisi.Editor.Controls.FLabel")
			{
				if (((Control)sender).Parent != null && ((Control)sender).Parent == this.FlowLayoutPanels[0])
				{
					foreach (Control control in this.flowLayoutPanel2.Controls)
					{
						if (control.GetType().ToString() == "Qisi.Editor.Controls.FLabel")
						{
							if (((FLabel)control).Ftype == e.Type)
							{
								this.flowLayoutPanel2.ScrollControlIntoView(control);
							}
						}
					}
				}
				if (((Control)sender).Parent != null && ((Control)sender).Parent.GetType().ToString() == "System.Windows.Forms.FlowLayoutPanel")
				{
					if (((Control)sender).Parent.Parent != null && ((Control)sender).Parent.Parent.GetType().ToString() == "Qisi.General.Controls.PopupHost")
					{
						((PopupHost)((Control)sender).Parent.Parent).Close();
					}
				}
			}
		}
		protected override void WndProc(ref Message m)
		{
			int msg = m.Msg;
			if (msg == 786)
			{
				if (this.id1 == (int)m.WParam)
				{
					Form form = base.FindForm();
					if (form != null && form.ActiveControl != null)
					{
						if (form.ActiveControl.GetType().ToString() == "Qisi.Editor.Controls.SuperBox")
						{
							((SuperBox)form.ActiveControl).AppendF(FType.分式);
						}
						else
						{
							Control control = this.ActiveSuperBox(form.ActiveControl);
							if (control != null)
							{
								((SuperBox)control).AppendF(FType.分式);
							}
						}
					}
				}
				else
				{
					if (this.id2 == (int)m.WParam)
					{
						Form form = base.FindForm();
						if (form != null && form.ActiveControl != null)
						{
							if (form.ActiveControl.GetType().ToString() == "Qisi.Editor.Controls.SuperBox")
							{
								((SuperBox)form.ActiveControl).AppendF(FType.上标);
							}
							else
							{
								Control control = this.ActiveSuperBox(form.ActiveControl);
								if (control != null)
								{
									((SuperBox)control).AppendF(FType.上标);
								}
							}
						}
					}
					else
					{
						if (this.id3 == (int)m.WParam)
						{
							Form form = base.FindForm();
							if (form != null && form.ActiveControl != null)
							{
								if (form.ActiveControl.GetType().ToString() == "Qisi.Editor.Controls.SuperBox")
								{
									((SuperBox)form.ActiveControl).AppendF(FType.下标);
								}
								else
								{
									Control control = this.ActiveSuperBox(form.ActiveControl);
									if (control != null)
									{
										((SuperBox)control).AppendF(FType.下标);
									}
								}
							}
						}
					}
				}
			}
			base.WndProc(ref m);
		}
		private Control ActiveSuperBox(Control c)
		{
			Control result;
			if (c is ContainerControl)
			{
				if (((ContainerControl)c).ActiveControl != null && ((ContainerControl)c).ActiveControl.GetType().ToString() == "Qisi.Editor.Controls.SuperBox")
				{
					result = ((ContainerControl)c).ActiveControl;
				}
				else
				{
					result = this.ActiveSuperBox(((ContainerControl)c).ActiveControl);
				}
			}
			else
			{
				result = null;
			}
			return result;
		}
		private void FormulaEditor_Click(object sender, EventArgs e)
		{
			if (sender.GetType().ToString() == "System.Windows.Forms.Label")
			{
				int num = this.Labels.IndexOf((Label)sender);
				if (num >= 0)
				{
					((Label)sender).BackColor = Color.LightCyan;
					this.PopupHosts[num + 1].Show(this.Labels[num], true);
				}
			}
		}
		private void flowLayoutPanel2_Scroll(object sender, ScrollEventArgs e)
		{
			this.PopupHosts[0].Show(this.flowLayoutPanel2);
		}
		private void FormulaEditor_Closed(object sender, ToolStripDropDownClosedEventArgs e)
		{
			if (sender.GetType().ToString() == "Qisi.General.Controls.PopupHost")
			{
				int num = this.PopupHosts.IndexOf((PopupHost)sender);
				if (num > 0)
				{
					this.Labels[num - 1].BackColor = Color.Transparent;
				}
			}
		}
		private void label3_Click(object sender, EventArgs e)
		{
		}
		protected override void Dispose(bool disposing)
		{
			NativeMethods.UnregisterHotKey(base.Handle, this.id1);
			NativeMethods.UnregisterHotKey(base.Handle, this.id2);
			NativeMethods.UnregisterHotKey(base.Handle, this.id3);
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}
		private void InitializeComponent()
		{
			this.components = new Container();
			this.toolTip1 = new ToolTip(this.components);
			this.flowLayoutPanel2 = new FlowLayoutPanel();
			this.flowLayoutPanel1 = new FlowLayoutPanel();
			this.label1 = new Label();
			this.label2 = new Label();
			base.SuspendLayout();
			this.flowLayoutPanel2.Location = new Point(4, 4);
			this.flowLayoutPanel2.Margin = new Padding(4);
			this.flowLayoutPanel2.Name = "flowLayoutPanel2";
			this.flowLayoutPanel2.Size = new Size(263, 82);
			this.flowLayoutPanel2.TabIndex = 4;
			this.flowLayoutPanel1.Location = new Point(275, 4);
			this.flowLayoutPanel1.Margin = new Padding(4);
			this.flowLayoutPanel1.Name = "flowLayoutPanel1";
			this.flowLayoutPanel1.Size = new Size(528, 82);
			this.flowLayoutPanel1.TabIndex = 7;
			this.label1.AutoSize = true;
			this.label1.Font = new Font("微软雅黑", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.label1.Location = new Point(120, 90);
			this.label1.Margin = new Padding(4, 0, 4, 0);
			this.label1.Name = "label1";
			this.label1.Size = new Size(65, 20);
			this.label1.TabIndex = 8;
			this.label1.Text = "通用符号";
			this.label1.TextAlign = ContentAlignment.MiddleCenter;
			this.label2.AutoSize = true;
			this.label2.Font = new Font("微软雅黑", 10.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.label2.Location = new Point(664, 90);
			this.label2.Margin = new Padding(4, 0, 4, 0);
			this.label2.Name = "label2";
			this.label2.Size = new Size(65, 20);
			this.label2.TabIndex = 9;
			this.label2.Text = "通用结构";
			this.label2.TextAlign = ContentAlignment.MiddleCenter;
			base.AutoScaleDimensions = new SizeF(6f, 12f);
			base.AutoScaleMode = AutoScaleMode.Font;
			this.BackColor = Color.FromArgb(194, 237, 223);
			base.BorderStyle = BorderStyle.FixedSingle;
			base.Controls.Add(this.label2);
			base.Controls.Add(this.label1);
			base.Controls.Add(this.flowLayoutPanel2);
			base.Controls.Add(this.flowLayoutPanel1);
			this.DoubleBuffered = true;
			base.Margin = new Padding(4);
			base.Name = "FormulaEditor";
			base.Size = new Size(812, 140);
			base.ResumeLayout(false);
			base.PerformLayout();
		}
	}
}
